#!/usr/bin/env bash
# Recover panel data after a rebrand upgrade that attached a fresh empty barn_pg
# while the real data stayed on a legacy Docker volume.
#
#   sudo bash scripts/recover-pg-volume.sh
#
set -euo pipefail

ROOT="${BARN_INSTALL_DIR:-${DOCK_PILOT_INSTALL_DIR:-/opt/barn}}"
cd "$ROOT"

log() { echo "[barn-recover] $*"; }
die() { echo "[barn-recover] ERROR: $*" >&2; exit 1; }

[[ -f .env ]] || die "no .env in $ROOT"
set -a
# shellcheck disable=SC1091
source ./.env
set +a

COMPOSE="docker-compose.barn-full.yml"
[[ -f "$COMPOSE" ]] || COMPOSE="docker-compose.barn.yml"
[[ -f "$COMPOSE" ]] || die "barn compose file not found in $ROOT"

log "Docker volumes matching postgres/barn/dock:"
docker volume ls --format '{{.Name}}' | grep -E 'pg|postgres|barn|dock' || true

LEGACY=""
for v in \
  dock-pilot_dock_pilot_pg \
  dock_pilot_pg \
  dockpilot-postgres-data \
  barn-postgres-data
do
  if docker volume inspect "$v" >/dev/null 2>&1; then
    LEGACY="$v"
    break
  fi
done
[[ -n "$LEGACY" ]] || die "no legacy Postgres volume found — list volumes above and tell support which one has data"

log "Will attach volume: $LEGACY"
OVERRIDE="${ROOT}/docker-compose.pg-volume.override.yml"
cat >"$OVERRIDE" <<EOF
# Generated by recover-pg-volume.sh
volumes:
  barn_pg:
    external: true
    name: ${LEGACY}
EOF

log "Stopping current postgres/api..."
docker compose -f "$COMPOSE" stop postgres api 2>/dev/null || true
docker rm -f barn-postgres dock-pilot-postgres dockpilot-postgres 2>/dev/null || true

log "Starting postgres on legacy volume..."
docker compose -f "$COMPOSE" -f "$OVERRIDE" up -d postgres

log "Waiting for postgres..."
for i in $(seq 1 30); do
  if docker compose -f "$COMPOSE" -f "$OVERRIDE" exec -T postgres \
    pg_isready -U "${POSTGRES_USER:-postgres}" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

log "Databases on recovered volume:"
docker compose -f "$COMPOSE" -f "$OVERRIDE" exec -T postgres \
  psql -U "${POSTGRES_USER:-postgres}" -d postgres -c \
  "SELECT datname FROM pg_database WHERE datistemplate = false ORDER BY 1" || \
docker compose -f "$COMPOSE" -f "$OVERRIDE" exec -T postgres \
  psql -U postgres -d postgres -c \
  "SELECT datname FROM pg_database WHERE datistemplate = false ORDER BY 1" || true

log "Site row counts (best-effort):"
for db in postgres barn dockpilot "${POSTGRES_DB:-}"; do
  [[ -z "$db" ]] && continue
  n="$(docker compose -f "$COMPOSE" -f "$OVERRIDE" exec -T postgres \
    psql -U "${POSTGRES_USER:-postgres}" -d "$db" -tAc 'SELECT count(*) FROM sites' 2>/dev/null || echo "")"
  [[ -n "$n" ]] && log "  $db.sites = $n"
done

log "Running migrations on recovered volume..."
docker compose -f "$COMPOSE" -f "$OVERRIDE" run --rm -T migrate || \
  log "WARN: migrate failed — check POSTGRES_USER/DB in .env match the volume"

log "Recreating api + frontend..."
docker compose -f "$COMPOSE" -f "$OVERRIDE" up -d --force-recreate api frontend

log "Done. Open the panel — settings/sites should be back."
log "Override kept at $OVERRIDE (upgrade will reuse it once fixed)."
