// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: backup_operations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBackupOperation = `-- name: CreateBackupOperation :one
INSERT INTO backup_operations (
    kind, status, database_name, instance_id, schedule_id, s3_key, size_bytes, message
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, kind, status, database_name, instance_id, schedule_id, s3_key, size_bytes, message, started_at, finished_at
`

type CreateBackupOperationParams struct {
	Kind         string      `json:"kind"`
	Status       string      `json:"status"`
	DatabaseName string      `json:"database_name"`
	InstanceID   pgtype.UUID `json:"instance_id"`
	ScheduleID   pgtype.UUID `json:"schedule_id"`
	S3Key        string      `json:"s3_key"`
	SizeBytes    int64       `json:"size_bytes"`
	Message      string      `json:"message"`
}

func (q *Queries) CreateBackupOperation(ctx context.Context, arg CreateBackupOperationParams) (BackupOperation, error) {
	row := q.db.QueryRow(ctx, createBackupOperation,
		arg.Kind,
		arg.Status,
		arg.DatabaseName,
		arg.InstanceID,
		arg.ScheduleID,
		arg.S3Key,
		arg.SizeBytes,
		arg.Message,
	)
	var i BackupOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.DatabaseName,
		&i.InstanceID,
		&i.ScheduleID,
		&i.S3Key,
		&i.SizeBytes,
		&i.Message,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishBackupOperation = `-- name: FinishBackupOperation :one
UPDATE backup_operations SET
    status = $2,
    s3_key = CASE WHEN $4::text <> '' THEN $4::text ELSE s3_key END,
    size_bytes = CASE WHEN $5::bigint > 0 THEN $5::bigint ELSE size_bytes END,
    message = $3,
    finished_at = now()
WHERE id = $1
RETURNING id, kind, status, database_name, instance_id, schedule_id, s3_key, size_bytes, message, started_at, finished_at
`

type FinishBackupOperationParams struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	Message   string    `json:"message"`
	S3Key     string    `json:"s3_key"`
	SizeBytes int64     `json:"size_bytes"`
}

func (q *Queries) FinishBackupOperation(ctx context.Context, arg FinishBackupOperationParams) (BackupOperation, error) {
	row := q.db.QueryRow(ctx, finishBackupOperation,
		arg.ID,
		arg.Status,
		arg.Message,
		arg.S3Key,
		arg.SizeBytes,
	)
	var i BackupOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.DatabaseName,
		&i.InstanceID,
		&i.ScheduleID,
		&i.S3Key,
		&i.SizeBytes,
		&i.Message,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listBackupOperations = `-- name: ListBackupOperations :many
SELECT id, kind, status, database_name, instance_id, schedule_id, s3_key, size_bytes, message, started_at, finished_at FROM backup_operations
ORDER BY started_at DESC
LIMIT $1
`

func (q *Queries) ListBackupOperations(ctx context.Context, limit int32) ([]BackupOperation, error) {
	rows, err := q.db.Query(ctx, listBackupOperations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupOperation{}
	for rows.Next() {
		var i BackupOperation
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.DatabaseName,
			&i.InstanceID,
			&i.ScheduleID,
			&i.S3Key,
			&i.SizeBytes,
			&i.Message,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
