// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: billing_accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBillingAccount = `-- name: CreateBillingAccount :one
INSERT INTO billing_accounts (
    provider, server_ip, login, encrypted_password, billmgr_url, alert_days, enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, provider, server_ip, login, encrypted_password, billmgr_url, alert_days, enabled, cached_expire_date, cached_status, cached_name, cached_cost, last_checked_at, last_check_error, last_alert_expire_date, last_alert_at, created_at, updated_at
`

type CreateBillingAccountParams struct {
	Provider          string `json:"provider"`
	ServerIp          string `json:"server_ip"`
	Login             string `json:"login"`
	EncryptedPassword []byte `json:"encrypted_password"`
	BillmgrUrl        string `json:"billmgr_url"`
	AlertDays         int32  `json:"alert_days"`
	Enabled           bool   `json:"enabled"`
}

func (q *Queries) CreateBillingAccount(ctx context.Context, arg CreateBillingAccountParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, createBillingAccount,
		arg.Provider,
		arg.ServerIp,
		arg.Login,
		arg.EncryptedPassword,
		arg.BillmgrUrl,
		arg.AlertDays,
		arg.Enabled,
	)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ServerIp,
		&i.Login,
		&i.EncryptedPassword,
		&i.BillmgrUrl,
		&i.AlertDays,
		&i.Enabled,
		&i.CachedExpireDate,
		&i.CachedStatus,
		&i.CachedName,
		&i.CachedCost,
		&i.LastCheckedAt,
		&i.LastCheckError,
		&i.LastAlertExpireDate,
		&i.LastAlertAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBillingAccount = `-- name: DeleteBillingAccount :exec
DELETE FROM billing_accounts WHERE id = $1
`

func (q *Queries) DeleteBillingAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBillingAccount, id)
	return err
}

const getBillingAccount = `-- name: GetBillingAccount :one
SELECT id, provider, server_ip, login, encrypted_password, billmgr_url, alert_days, enabled, cached_expire_date, cached_status, cached_name, cached_cost, last_checked_at, last_check_error, last_alert_expire_date, last_alert_at, created_at, updated_at FROM billing_accounts WHERE id = $1
`

func (q *Queries) GetBillingAccount(ctx context.Context, id uuid.UUID) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, getBillingAccount, id)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ServerIp,
		&i.Login,
		&i.EncryptedPassword,
		&i.BillmgrUrl,
		&i.AlertDays,
		&i.Enabled,
		&i.CachedExpireDate,
		&i.CachedStatus,
		&i.CachedName,
		&i.CachedCost,
		&i.LastCheckedAt,
		&i.LastCheckError,
		&i.LastAlertExpireDate,
		&i.LastAlertAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBillingAccounts = `-- name: ListBillingAccounts :many
SELECT id, provider, server_ip, login, encrypted_password, billmgr_url, alert_days, enabled, cached_expire_date, cached_status, cached_name, cached_cost, last_checked_at, last_check_error, last_alert_expire_date, last_alert_at, created_at, updated_at FROM billing_accounts
ORDER BY server_ip ASC
`

func (q *Queries) ListBillingAccounts(ctx context.Context) ([]BillingAccount, error) {
	rows, err := q.db.Query(ctx, listBillingAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingAccount{}
	for rows.Next() {
		var i BillingAccount
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ServerIp,
			&i.Login,
			&i.EncryptedPassword,
			&i.BillmgrUrl,
			&i.AlertDays,
			&i.Enabled,
			&i.CachedExpireDate,
			&i.CachedStatus,
			&i.CachedName,
			&i.CachedCost,
			&i.LastCheckedAt,
			&i.LastCheckError,
			&i.LastAlertExpireDate,
			&i.LastAlertAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledBillingAccounts = `-- name: ListEnabledBillingAccounts :many
SELECT id, provider, server_ip, login, encrypted_password, billmgr_url, alert_days, enabled, cached_expire_date, cached_status, cached_name, cached_cost, last_checked_at, last_check_error, last_alert_expire_date, last_alert_at, created_at, updated_at FROM billing_accounts
WHERE enabled = true
ORDER BY server_ip ASC
`

func (q *Queries) ListEnabledBillingAccounts(ctx context.Context) ([]BillingAccount, error) {
	rows, err := q.db.Query(ctx, listEnabledBillingAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingAccount{}
	for rows.Next() {
		var i BillingAccount
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ServerIp,
			&i.Login,
			&i.EncryptedPassword,
			&i.BillmgrUrl,
			&i.AlertDays,
			&i.Enabled,
			&i.CachedExpireDate,
			&i.CachedStatus,
			&i.CachedName,
			&i.CachedCost,
			&i.LastCheckedAt,
			&i.LastCheckError,
			&i.LastAlertExpireDate,
			&i.LastAlertAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBillingAccountAlerted = `-- name: MarkBillingAccountAlerted :one
UPDATE billing_accounts SET
    last_alert_expire_date = $2,
    last_alert_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, provider, server_ip, login, encrypted_password, billmgr_url, alert_days, enabled, cached_expire_date, cached_status, cached_name, cached_cost, last_checked_at, last_check_error, last_alert_expire_date, last_alert_at, created_at, updated_at
`

type MarkBillingAccountAlertedParams struct {
	ID                  uuid.UUID   `json:"id"`
	LastAlertExpireDate pgtype.Date `json:"last_alert_expire_date"`
}

func (q *Queries) MarkBillingAccountAlerted(ctx context.Context, arg MarkBillingAccountAlertedParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, markBillingAccountAlerted, arg.ID, arg.LastAlertExpireDate)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ServerIp,
		&i.Login,
		&i.EncryptedPassword,
		&i.BillmgrUrl,
		&i.AlertDays,
		&i.Enabled,
		&i.CachedExpireDate,
		&i.CachedStatus,
		&i.CachedName,
		&i.CachedCost,
		&i.LastCheckedAt,
		&i.LastCheckError,
		&i.LastAlertExpireDate,
		&i.LastAlertAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBillingAccount = `-- name: UpdateBillingAccount :one
UPDATE billing_accounts SET
    provider = $2,
    server_ip = $3,
    login = $4,
    billmgr_url = $5,
    alert_days = $6,
    enabled = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, provider, server_ip, login, encrypted_password, billmgr_url, alert_days, enabled, cached_expire_date, cached_status, cached_name, cached_cost, last_checked_at, last_check_error, last_alert_expire_date, last_alert_at, created_at, updated_at
`

type UpdateBillingAccountParams struct {
	ID         uuid.UUID `json:"id"`
	Provider   string    `json:"provider"`
	ServerIp   string    `json:"server_ip"`
	Login      string    `json:"login"`
	BillmgrUrl string    `json:"billmgr_url"`
	AlertDays  int32     `json:"alert_days"`
	Enabled    bool      `json:"enabled"`
}

func (q *Queries) UpdateBillingAccount(ctx context.Context, arg UpdateBillingAccountParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, updateBillingAccount,
		arg.ID,
		arg.Provider,
		arg.ServerIp,
		arg.Login,
		arg.BillmgrUrl,
		arg.AlertDays,
		arg.Enabled,
	)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ServerIp,
		&i.Login,
		&i.EncryptedPassword,
		&i.BillmgrUrl,
		&i.AlertDays,
		&i.Enabled,
		&i.CachedExpireDate,
		&i.CachedStatus,
		&i.CachedName,
		&i.CachedCost,
		&i.LastCheckedAt,
		&i.LastCheckError,
		&i.LastAlertExpireDate,
		&i.LastAlertAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBillingAccountCache = `-- name: UpdateBillingAccountCache :one
UPDATE billing_accounts SET
    cached_expire_date = $2,
    cached_status = $3,
    cached_name = $4,
    cached_cost = $5,
    last_checked_at = now(),
    last_check_error = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, provider, server_ip, login, encrypted_password, billmgr_url, alert_days, enabled, cached_expire_date, cached_status, cached_name, cached_cost, last_checked_at, last_check_error, last_alert_expire_date, last_alert_at, created_at, updated_at
`

type UpdateBillingAccountCacheParams struct {
	ID               uuid.UUID   `json:"id"`
	CachedExpireDate pgtype.Date `json:"cached_expire_date"`
	CachedStatus     string      `json:"cached_status"`
	CachedName       string      `json:"cached_name"`
	CachedCost       string      `json:"cached_cost"`
	LastCheckError   string      `json:"last_check_error"`
}

func (q *Queries) UpdateBillingAccountCache(ctx context.Context, arg UpdateBillingAccountCacheParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, updateBillingAccountCache,
		arg.ID,
		arg.CachedExpireDate,
		arg.CachedStatus,
		arg.CachedName,
		arg.CachedCost,
		arg.LastCheckError,
	)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ServerIp,
		&i.Login,
		&i.EncryptedPassword,
		&i.BillmgrUrl,
		&i.AlertDays,
		&i.Enabled,
		&i.CachedExpireDate,
		&i.CachedStatus,
		&i.CachedName,
		&i.CachedCost,
		&i.LastCheckedAt,
		&i.LastCheckError,
		&i.LastAlertExpireDate,
		&i.LastAlertAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBillingAccountPassword = `-- name: UpdateBillingAccountPassword :one
UPDATE billing_accounts SET
    encrypted_password = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, provider, server_ip, login, encrypted_password, billmgr_url, alert_days, enabled, cached_expire_date, cached_status, cached_name, cached_cost, last_checked_at, last_check_error, last_alert_expire_date, last_alert_at, created_at, updated_at
`

type UpdateBillingAccountPasswordParams struct {
	ID                uuid.UUID `json:"id"`
	EncryptedPassword []byte    `json:"encrypted_password"`
}

func (q *Queries) UpdateBillingAccountPassword(ctx context.Context, arg UpdateBillingAccountPasswordParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, updateBillingAccountPassword, arg.ID, arg.EncryptedPassword)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ServerIp,
		&i.Login,
		&i.EncryptedPassword,
		&i.BillmgrUrl,
		&i.AlertDays,
		&i.Enabled,
		&i.CachedExpireDate,
		&i.CachedStatus,
		&i.CachedName,
		&i.CachedCost,
		&i.LastCheckedAt,
		&i.LastCheckError,
		&i.LastAlertExpireDate,
		&i.LastAlertAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
