// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Deployment struct {
	ID         uuid.UUID          `json:"id"`
	SiteID     uuid.UUID          `json:"site_id"`
	Status     string             `json:"status"`
	Message    string             `json:"message"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type DeploymentLog struct {
	ID           int64     `json:"id"`
	DeploymentID uuid.UUID `json:"deployment_id"`
	Level        string    `json:"level"`
	Message      string    `json:"message"`
	CreatedAt    time.Time `json:"created_at"`
}

type NotificationSetting struct {
	ID                        int32              `json:"id"`
	Enabled                   bool               `json:"enabled"`
	TelegramChatID            string             `json:"telegram_chat_id"`
	TelegramHttpProxy         string             `json:"telegram_http_proxy"`
	DailyDigestEnabled        bool               `json:"daily_digest_enabled"`
	DailyDigestHour           int32              `json:"daily_digest_hour"`
	DailyDigestTimezone       string             `json:"daily_digest_timezone"`
	AlertOnIncidentEnabled    bool               `json:"alert_on_incident_enabled"`
	EncryptedTelegramBotToken []byte             `json:"encrypted_telegram_bot_token"`
	LastDailySentAt           pgtype.Timestamptz `json:"last_daily_sent_at"`
	LastOverallBySite         []byte             `json:"last_overall_by_site"`
	UpdatedAt                 time.Time          `json:"updated_at"`
}

type PanelBackupSetting struct {
	ID                   int32              `json:"id"`
	Enabled              bool               `json:"enabled"`
	Hour                 int32              `json:"hour"`
	Minute               int32              `json:"minute"`
	Timezone             string             `json:"timezone"`
	S3Endpoint           string             `json:"s3_endpoint"`
	S3Region             string             `json:"s3_region"`
	S3Bucket             string             `json:"s3_bucket"`
	S3Prefix             string             `json:"s3_prefix"`
	EncryptedS3AccessKey []byte             `json:"encrypted_s3_access_key"`
	EncryptedS3SecretKey []byte             `json:"encrypted_s3_secret_key"`
	S3ForcePathStyle     bool               `json:"s3_force_path_style"`
	RetentionCount       int32              `json:"retention_count"`
	LastRunAt            pgtype.Timestamptz `json:"last_run_at"`
	LastStatus           string             `json:"last_status"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type PdbBackupSchedule struct {
	ID                   uuid.UUID          `json:"id"`
	InstanceID           uuid.UUID          `json:"instance_id"`
	DatabaseID           pgtype.UUID        `json:"database_id"`
	Enabled              bool               `json:"enabled"`
	Hour                 int32              `json:"hour"`
	Minute               int32              `json:"minute"`
	Timezone             string             `json:"timezone"`
	S3Endpoint           string             `json:"s3_endpoint"`
	S3Region             string             `json:"s3_region"`
	S3Bucket             string             `json:"s3_bucket"`
	S3Prefix             string             `json:"s3_prefix"`
	EncryptedS3AccessKey []byte             `json:"encrypted_s3_access_key"`
	EncryptedS3SecretKey []byte             `json:"encrypted_s3_secret_key"`
	S3ForcePathStyle     bool               `json:"s3_force_path_style"`
	RetentionCount       int32              `json:"retention_count"`
	LastRunAt            pgtype.Timestamptz `json:"last_run_at"`
	LastStatus           string             `json:"last_status"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type PdbDatabase struct {
	ID         uuid.UUID `json:"id"`
	InstanceID uuid.UUID `json:"instance_id"`
	Name       string    `json:"name"`
	OwnerRole  string    `json:"owner_role"`
	CreatedAt  time.Time `json:"created_at"`
}

type PdbInstance struct {
	ID                     uuid.UUID   `json:"id"`
	Name                   string      `json:"name"`
	Slug                   string      `json:"slug"`
	Image                  string      `json:"image"`
	ContainerPort          int32       `json:"container_port"`
	HostPort               pgtype.Int4 `json:"host_port"`
	DockerNetworkHost      bool        `json:"docker_network_host"`
	AdminUser              string      `json:"admin_user"`
	EncryptedAdminPassword []byte      `json:"encrypted_admin_password"`
	Status                 string      `json:"status"`
	Message                string      `json:"message"`
	CreatedAt              time.Time   `json:"created_at"`
	UpdatedAt              time.Time   `json:"updated_at"`
}

type PdbRole struct {
	ID                uuid.UUID `json:"id"`
	InstanceID        uuid.UUID `json:"instance_id"`
	Name              string    `json:"name"`
	EncryptedPassword []byte    `json:"encrypted_password"`
	CreatedAt         time.Time `json:"created_at"`
}

type PdbRoleGrant struct {
	ID         uuid.UUID `json:"id"`
	RoleID     uuid.UUID `json:"role_id"`
	DatabaseID uuid.UUID `json:"database_id"`
	IsOwner    bool      `json:"is_owner"`
}

type Site struct {
	ID                 uuid.UUID   `json:"id"`
	Name               string      `json:"name"`
	Slug               string      `json:"slug"`
	PrimaryUrl         string      `json:"primary_url"`
	GitRepoUrl         string      `json:"git_repo_url"`
	GitBranch          string      `json:"git_branch"`
	DockerfilePath     string      `json:"dockerfile_path"`
	BuildContext       string      `json:"build_context"`
	ContainerPort      int32       `json:"container_port"`
	HostPort           pgtype.Int4 `json:"host_port"`
	NginxSslEnabled    bool        `json:"nginx_ssl_enabled"`
	NginxForceHttps    bool        `json:"nginx_force_https"`
	SiteType           string      `json:"site_type"`
	DockerVolumeMounts string      `json:"docker_volume_mounts"`
	DockerNamedVolumes string      `json:"docker_named_volumes"`
	DockerNetworkHost  bool        `json:"docker_network_host"`
	HealthCheckPath    string      `json:"health_check_path"`
	Status             string      `json:"status"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

type SiteDomain struct {
	ID        uuid.UUID `json:"id"`
	SiteID    uuid.UUID `json:"site_id"`
	Domain    string    `json:"domain"`
	IsPrimary bool      `json:"is_primary"`
	CreatedAt time.Time `json:"created_at"`
}

type SiteEnvVar struct {
	ID        uuid.UUID `json:"id"`
	SiteID    uuid.UUID `json:"site_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SiteSecret struct {
	ID             uuid.UUID `json:"id"`
	SiteID         uuid.UUID `json:"site_id"`
	Key            string    `json:"key"`
	EncryptedValue []byte    `json:"encrypted_value"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
