// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: panel_backup_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPanelBackupS3Keys = `-- name: ClearPanelBackupS3Keys :one
UPDATE panel_backup_settings SET
    encrypted_s3_access_key = NULL,
    encrypted_s3_secret_key = NULL,
    updated_at = now()
WHERE id = 1
RETURNING id, enabled, hour, minute, timezone, s3_endpoint, s3_region, s3_bucket, s3_prefix, encrypted_s3_access_key, encrypted_s3_secret_key, s3_force_path_style, retention_count, last_run_at, last_status, updated_at
`

func (q *Queries) ClearPanelBackupS3Keys(ctx context.Context) (PanelBackupSetting, error) {
	row := q.db.QueryRow(ctx, clearPanelBackupS3Keys)
	var i PanelBackupSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Hour,
		&i.Minute,
		&i.Timezone,
		&i.S3Endpoint,
		&i.S3Region,
		&i.S3Bucket,
		&i.S3Prefix,
		&i.EncryptedS3AccessKey,
		&i.EncryptedS3SecretKey,
		&i.S3ForcePathStyle,
		&i.RetentionCount,
		&i.LastRunAt,
		&i.LastStatus,
		&i.UpdatedAt,
	)
	return i, err
}

const ensurePanelBackupSettings = `-- name: EnsurePanelBackupSettings :one
INSERT INTO panel_backup_settings (id) VALUES (1)
ON CONFLICT (id) DO UPDATE SET updated_at = panel_backup_settings.updated_at
RETURNING id, enabled, hour, minute, timezone, s3_endpoint, s3_region, s3_bucket, s3_prefix, encrypted_s3_access_key, encrypted_s3_secret_key, s3_force_path_style, retention_count, last_run_at, last_status, updated_at
`

func (q *Queries) EnsurePanelBackupSettings(ctx context.Context) (PanelBackupSetting, error) {
	row := q.db.QueryRow(ctx, ensurePanelBackupSettings)
	var i PanelBackupSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Hour,
		&i.Minute,
		&i.Timezone,
		&i.S3Endpoint,
		&i.S3Region,
		&i.S3Bucket,
		&i.S3Prefix,
		&i.EncryptedS3AccessKey,
		&i.EncryptedS3SecretKey,
		&i.S3ForcePathStyle,
		&i.RetentionCount,
		&i.LastRunAt,
		&i.LastStatus,
		&i.UpdatedAt,
	)
	return i, err
}

const getPanelBackupSettings = `-- name: GetPanelBackupSettings :one
SELECT id, enabled, hour, minute, timezone, s3_endpoint, s3_region, s3_bucket, s3_prefix, encrypted_s3_access_key, encrypted_s3_secret_key, s3_force_path_style, retention_count, last_run_at, last_status, updated_at FROM panel_backup_settings WHERE id = 1
`

func (q *Queries) GetPanelBackupSettings(ctx context.Context) (PanelBackupSetting, error) {
	row := q.db.QueryRow(ctx, getPanelBackupSettings)
	var i PanelBackupSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Hour,
		&i.Minute,
		&i.Timezone,
		&i.S3Endpoint,
		&i.S3Region,
		&i.S3Bucket,
		&i.S3Prefix,
		&i.EncryptedS3AccessKey,
		&i.EncryptedS3SecretKey,
		&i.S3ForcePathStyle,
		&i.RetentionCount,
		&i.LastRunAt,
		&i.LastStatus,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePanelBackupRun = `-- name: UpdatePanelBackupRun :one
UPDATE panel_backup_settings SET
    last_run_at = $1,
    last_status = $2,
    updated_at = now()
WHERE id = 1
RETURNING id, enabled, hour, minute, timezone, s3_endpoint, s3_region, s3_bucket, s3_prefix, encrypted_s3_access_key, encrypted_s3_secret_key, s3_force_path_style, retention_count, last_run_at, last_status, updated_at
`

type UpdatePanelBackupRunParams struct {
	LastRunAt  pgtype.Timestamptz `json:"last_run_at"`
	LastStatus string             `json:"last_status"`
}

func (q *Queries) UpdatePanelBackupRun(ctx context.Context, arg UpdatePanelBackupRunParams) (PanelBackupSetting, error) {
	row := q.db.QueryRow(ctx, updatePanelBackupRun, arg.LastRunAt, arg.LastStatus)
	var i PanelBackupSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Hour,
		&i.Minute,
		&i.Timezone,
		&i.S3Endpoint,
		&i.S3Region,
		&i.S3Bucket,
		&i.S3Prefix,
		&i.EncryptedS3AccessKey,
		&i.EncryptedS3SecretKey,
		&i.S3ForcePathStyle,
		&i.RetentionCount,
		&i.LastRunAt,
		&i.LastStatus,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePanelBackupS3Keys = `-- name: UpdatePanelBackupS3Keys :one
UPDATE panel_backup_settings SET
    encrypted_s3_access_key = $1,
    encrypted_s3_secret_key = $2,
    updated_at = now()
WHERE id = 1
RETURNING id, enabled, hour, minute, timezone, s3_endpoint, s3_region, s3_bucket, s3_prefix, encrypted_s3_access_key, encrypted_s3_secret_key, s3_force_path_style, retention_count, last_run_at, last_status, updated_at
`

type UpdatePanelBackupS3KeysParams struct {
	EncryptedS3AccessKey []byte `json:"encrypted_s3_access_key"`
	EncryptedS3SecretKey []byte `json:"encrypted_s3_secret_key"`
}

func (q *Queries) UpdatePanelBackupS3Keys(ctx context.Context, arg UpdatePanelBackupS3KeysParams) (PanelBackupSetting, error) {
	row := q.db.QueryRow(ctx, updatePanelBackupS3Keys, arg.EncryptedS3AccessKey, arg.EncryptedS3SecretKey)
	var i PanelBackupSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Hour,
		&i.Minute,
		&i.Timezone,
		&i.S3Endpoint,
		&i.S3Region,
		&i.S3Bucket,
		&i.S3Prefix,
		&i.EncryptedS3AccessKey,
		&i.EncryptedS3SecretKey,
		&i.S3ForcePathStyle,
		&i.RetentionCount,
		&i.LastRunAt,
		&i.LastStatus,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePanelBackupSettings = `-- name: UpdatePanelBackupSettings :one
UPDATE panel_backup_settings SET
    enabled = $1,
    hour = $2,
    minute = $3,
    timezone = $4,
    s3_endpoint = $5,
    s3_region = $6,
    s3_bucket = $7,
    s3_prefix = $8,
    s3_force_path_style = $9,
    retention_count = $10,
    updated_at = now()
WHERE id = 1
RETURNING id, enabled, hour, minute, timezone, s3_endpoint, s3_region, s3_bucket, s3_prefix, encrypted_s3_access_key, encrypted_s3_secret_key, s3_force_path_style, retention_count, last_run_at, last_status, updated_at
`

type UpdatePanelBackupSettingsParams struct {
	Enabled          bool   `json:"enabled"`
	Hour             int32  `json:"hour"`
	Minute           int32  `json:"minute"`
	Timezone         string `json:"timezone"`
	S3Endpoint       string `json:"s3_endpoint"`
	S3Region         string `json:"s3_region"`
	S3Bucket         string `json:"s3_bucket"`
	S3Prefix         string `json:"s3_prefix"`
	S3ForcePathStyle bool   `json:"s3_force_path_style"`
	RetentionCount   int32  `json:"retention_count"`
}

func (q *Queries) UpdatePanelBackupSettings(ctx context.Context, arg UpdatePanelBackupSettingsParams) (PanelBackupSetting, error) {
	row := q.db.QueryRow(ctx, updatePanelBackupSettings,
		arg.Enabled,
		arg.Hour,
		arg.Minute,
		arg.Timezone,
		arg.S3Endpoint,
		arg.S3Region,
		arg.S3Bucket,
		arg.S3Prefix,
		arg.S3ForcePathStyle,
		arg.RetentionCount,
	)
	var i PanelBackupSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Hour,
		&i.Minute,
		&i.Timezone,
		&i.S3Endpoint,
		&i.S3Region,
		&i.S3Bucket,
		&i.S3Prefix,
		&i.EncryptedS3AccessKey,
		&i.EncryptedS3SecretKey,
		&i.S3ForcePathStyle,
		&i.RetentionCount,
		&i.LastRunAt,
		&i.LastStatus,
		&i.UpdatedAt,
	)
	return i, err
}
