// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pdb_database_activity.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const upsertPdbDatabaseActivity = `-- name: UpsertPdbDatabaseActivity :one
INSERT INTO pdb_database_activity (
    instance_id, database_name, inserts, updates, deletes, checked_at
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (instance_id, database_name) DO UPDATE SET
    last_dml_at = CASE
        WHEN EXCLUDED.inserts > pdb_database_activity.inserts
          OR EXCLUDED.updates > pdb_database_activity.updates
          OR EXCLUDED.deletes > pdb_database_activity.deletes
        THEN EXCLUDED.checked_at
        ELSE pdb_database_activity.last_dml_at
    END,
    inserts = EXCLUDED.inserts,
    updates = EXCLUDED.updates,
    deletes = EXCLUDED.deletes,
    checked_at = EXCLUDED.checked_at
RETURNING instance_id, database_name, inserts, updates, deletes, last_dml_at, checked_at
`

type UpsertPdbDatabaseActivityParams struct {
	InstanceID   uuid.UUID `json:"instance_id"`
	DatabaseName string    `json:"database_name"`
	Inserts      int64     `json:"inserts"`
	Updates      int64     `json:"updates"`
	Deletes      int64     `json:"deletes"`
	CheckedAt    time.Time `json:"checked_at"`
}

func (q *Queries) UpsertPdbDatabaseActivity(ctx context.Context, arg UpsertPdbDatabaseActivityParams) (PdbDatabaseActivity, error) {
	row := q.db.QueryRow(ctx, upsertPdbDatabaseActivity,
		arg.InstanceID,
		arg.DatabaseName,
		arg.Inserts,
		arg.Updates,
		arg.Deletes,
		arg.CheckedAt,
	)
	var i PdbDatabaseActivity
	err := row.Scan(
		&i.InstanceID,
		&i.DatabaseName,
		&i.Inserts,
		&i.Updates,
		&i.Deletes,
		&i.LastDmlAt,
		&i.CheckedAt,
	)
	return i, err
}
