// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pg_databases.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPgBackupSchedule = `-- name: CreatePgBackupSchedule :one
INSERT INTO pdb_backup_schedules (
    instance_id, database_id, enabled, hour, minute, timezone,
    s3_endpoint, s3_region, s3_bucket, s3_prefix,
    encrypted_s3_access_key, encrypted_s3_secret_key, s3_force_path_style,
    retention_count
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, instance_id, database_id, enabled, hour, minute, timezone, s3_endpoint, s3_region, s3_bucket, s3_prefix, encrypted_s3_access_key, encrypted_s3_secret_key, s3_force_path_style, retention_count, last_run_at, last_status, created_at, updated_at
`

type CreatePgBackupScheduleParams struct {
	InstanceID           uuid.UUID   `json:"instance_id"`
	DatabaseID           pgtype.UUID `json:"database_id"`
	Enabled              bool        `json:"enabled"`
	Hour                 int32       `json:"hour"`
	Minute               int32       `json:"minute"`
	Timezone             string      `json:"timezone"`
	S3Endpoint           string      `json:"s3_endpoint"`
	S3Region             string      `json:"s3_region"`
	S3Bucket             string      `json:"s3_bucket"`
	S3Prefix             string      `json:"s3_prefix"`
	EncryptedS3AccessKey []byte      `json:"encrypted_s3_access_key"`
	EncryptedS3SecretKey []byte      `json:"encrypted_s3_secret_key"`
	S3ForcePathStyle     bool        `json:"s3_force_path_style"`
	RetentionCount       int32       `json:"retention_count"`
}

func (q *Queries) CreatePgBackupSchedule(ctx context.Context, arg CreatePgBackupScheduleParams) (PdbBackupSchedule, error) {
	row := q.db.QueryRow(ctx, createPgBackupSchedule,
		arg.InstanceID,
		arg.DatabaseID,
		arg.Enabled,
		arg.Hour,
		arg.Minute,
		arg.Timezone,
		arg.S3Endpoint,
		arg.S3Region,
		arg.S3Bucket,
		arg.S3Prefix,
		arg.EncryptedS3AccessKey,
		arg.EncryptedS3SecretKey,
		arg.S3ForcePathStyle,
		arg.RetentionCount,
	)
	var i PdbBackupSchedule
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.DatabaseID,
		&i.Enabled,
		&i.Hour,
		&i.Minute,
		&i.Timezone,
		&i.S3Endpoint,
		&i.S3Region,
		&i.S3Bucket,
		&i.S3Prefix,
		&i.EncryptedS3AccessKey,
		&i.EncryptedS3SecretKey,
		&i.S3ForcePathStyle,
		&i.RetentionCount,
		&i.LastRunAt,
		&i.LastStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPgDatabase = `-- name: CreatePgDatabase :one
INSERT INTO pdb_databases (instance_id, name, owner_role)
VALUES ($1, $2, $3)
RETURNING id, instance_id, name, owner_role, created_at
`

type CreatePgDatabaseParams struct {
	InstanceID uuid.UUID `json:"instance_id"`
	Name       string    `json:"name"`
	OwnerRole  string    `json:"owner_role"`
}

func (q *Queries) CreatePgDatabase(ctx context.Context, arg CreatePgDatabaseParams) (PdbDatabase, error) {
	row := q.db.QueryRow(ctx, createPgDatabase, arg.InstanceID, arg.Name, arg.OwnerRole)
	var i PdbDatabase
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.OwnerRole,
		&i.CreatedAt,
	)
	return i, err
}

const createPgInstance = `-- name: CreatePgInstance :one
INSERT INTO pdb_instances (
    name, slug, image, container_port, host_port, docker_network_host,
    admin_user, encrypted_admin_password, status, message
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, name, slug, image, container_port, host_port, docker_network_host, admin_user, encrypted_admin_password, status, message, created_at, updated_at
`

type CreatePgInstanceParams struct {
	Name                   string      `json:"name"`
	Slug                   string      `json:"slug"`
	Image                  string      `json:"image"`
	ContainerPort          int32       `json:"container_port"`
	HostPort               pgtype.Int4 `json:"host_port"`
	DockerNetworkHost      bool        `json:"docker_network_host"`
	AdminUser              string      `json:"admin_user"`
	EncryptedAdminPassword []byte      `json:"encrypted_admin_password"`
	Status                 string      `json:"status"`
	Message                string      `json:"message"`
}

func (q *Queries) CreatePgInstance(ctx context.Context, arg CreatePgInstanceParams) (PdbInstance, error) {
	row := q.db.QueryRow(ctx, createPgInstance,
		arg.Name,
		arg.Slug,
		arg.Image,
		arg.ContainerPort,
		arg.HostPort,
		arg.DockerNetworkHost,
		arg.AdminUser,
		arg.EncryptedAdminPassword,
		arg.Status,
		arg.Message,
	)
	var i PdbInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Image,
		&i.ContainerPort,
		&i.HostPort,
		&i.DockerNetworkHost,
		&i.AdminUser,
		&i.EncryptedAdminPassword,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPgRole = `-- name: CreatePgRole :one
INSERT INTO pdb_roles (instance_id, name, encrypted_password)
VALUES ($1, $2, $3)
RETURNING id, instance_id, name, encrypted_password, created_at
`

type CreatePgRoleParams struct {
	InstanceID        uuid.UUID `json:"instance_id"`
	Name              string    `json:"name"`
	EncryptedPassword []byte    `json:"encrypted_password"`
}

func (q *Queries) CreatePgRole(ctx context.Context, arg CreatePgRoleParams) (PdbRole, error) {
	row := q.db.QueryRow(ctx, createPgRole, arg.InstanceID, arg.Name, arg.EncryptedPassword)
	var i PdbRole
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.EncryptedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const deletePgBackupSchedule = `-- name: DeletePgBackupSchedule :exec
DELETE FROM pdb_backup_schedules WHERE id = $1
`

func (q *Queries) DeletePgBackupSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePgBackupSchedule, id)
	return err
}

const deletePgDatabase = `-- name: DeletePgDatabase :exec
DELETE FROM pdb_databases WHERE id = $1
`

func (q *Queries) DeletePgDatabase(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePgDatabase, id)
	return err
}

const deletePgInstance = `-- name: DeletePgInstance :exec
DELETE FROM pdb_instances WHERE id = $1
`

func (q *Queries) DeletePgInstance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePgInstance, id)
	return err
}

const deletePgRole = `-- name: DeletePgRole :exec
DELETE FROM pdb_roles WHERE id = $1
`

func (q *Queries) DeletePgRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePgRole, id)
	return err
}

const deletePgRoleGrant = `-- name: DeletePgRoleGrant :exec
DELETE FROM pdb_role_grants WHERE role_id = $1 AND database_id = $2
`

type DeletePgRoleGrantParams struct {
	RoleID     uuid.UUID `json:"role_id"`
	DatabaseID uuid.UUID `json:"database_id"`
}

func (q *Queries) DeletePgRoleGrant(ctx context.Context, arg DeletePgRoleGrantParams) error {
	_, err := q.db.Exec(ctx, deletePgRoleGrant, arg.RoleID, arg.DatabaseID)
	return err
}

const getPgBackupSchedule = `-- name: GetPgBackupSchedule :one
SELECT id, instance_id, database_id, enabled, hour, minute, timezone, s3_endpoint, s3_region, s3_bucket, s3_prefix, encrypted_s3_access_key, encrypted_s3_secret_key, s3_force_path_style, retention_count, last_run_at, last_status, created_at, updated_at FROM pdb_backup_schedules WHERE id = $1
`

func (q *Queries) GetPgBackupSchedule(ctx context.Context, id uuid.UUID) (PdbBackupSchedule, error) {
	row := q.db.QueryRow(ctx, getPgBackupSchedule, id)
	var i PdbBackupSchedule
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.DatabaseID,
		&i.Enabled,
		&i.Hour,
		&i.Minute,
		&i.Timezone,
		&i.S3Endpoint,
		&i.S3Region,
		&i.S3Bucket,
		&i.S3Prefix,
		&i.EncryptedS3AccessKey,
		&i.EncryptedS3SecretKey,
		&i.S3ForcePathStyle,
		&i.RetentionCount,
		&i.LastRunAt,
		&i.LastStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPgDatabase = `-- name: GetPgDatabase :one
SELECT id, instance_id, name, owner_role, created_at FROM pdb_databases WHERE id = $1
`

func (q *Queries) GetPgDatabase(ctx context.Context, id uuid.UUID) (PdbDatabase, error) {
	row := q.db.QueryRow(ctx, getPgDatabase, id)
	var i PdbDatabase
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.OwnerRole,
		&i.CreatedAt,
	)
	return i, err
}

const getPgInstance = `-- name: GetPgInstance :one
SELECT id, name, slug, image, container_port, host_port, docker_network_host, admin_user, encrypted_admin_password, status, message, created_at, updated_at FROM pdb_instances WHERE id = $1
`

func (q *Queries) GetPgInstance(ctx context.Context, id uuid.UUID) (PdbInstance, error) {
	row := q.db.QueryRow(ctx, getPgInstance, id)
	var i PdbInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Image,
		&i.ContainerPort,
		&i.HostPort,
		&i.DockerNetworkHost,
		&i.AdminUser,
		&i.EncryptedAdminPassword,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPgInstanceBySlug = `-- name: GetPgInstanceBySlug :one
SELECT id, name, slug, image, container_port, host_port, docker_network_host, admin_user, encrypted_admin_password, status, message, created_at, updated_at FROM pdb_instances WHERE slug = $1
`

func (q *Queries) GetPgInstanceBySlug(ctx context.Context, slug string) (PdbInstance, error) {
	row := q.db.QueryRow(ctx, getPgInstanceBySlug, slug)
	var i PdbInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Image,
		&i.ContainerPort,
		&i.HostPort,
		&i.DockerNetworkHost,
		&i.AdminUser,
		&i.EncryptedAdminPassword,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPgRole = `-- name: GetPgRole :one
SELECT id, instance_id, name, encrypted_password, created_at FROM pdb_roles WHERE id = $1
`

func (q *Queries) GetPgRole(ctx context.Context, id uuid.UUID) (PdbRole, error) {
	row := q.db.QueryRow(ctx, getPgRole, id)
	var i PdbRole
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.EncryptedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledPgBackupSchedules = `-- name: ListEnabledPgBackupSchedules :many
SELECT id, instance_id, database_id, enabled, hour, minute, timezone, s3_endpoint, s3_region, s3_bucket, s3_prefix, encrypted_s3_access_key, encrypted_s3_secret_key, s3_force_path_style, retention_count, last_run_at, last_status, created_at, updated_at FROM pdb_backup_schedules WHERE enabled = true ORDER BY created_at ASC
`

func (q *Queries) ListEnabledPgBackupSchedules(ctx context.Context) ([]PdbBackupSchedule, error) {
	rows, err := q.db.Query(ctx, listEnabledPgBackupSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PdbBackupSchedule{}
	for rows.Next() {
		var i PdbBackupSchedule
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.DatabaseID,
			&i.Enabled,
			&i.Hour,
			&i.Minute,
			&i.Timezone,
			&i.S3Endpoint,
			&i.S3Region,
			&i.S3Bucket,
			&i.S3Prefix,
			&i.EncryptedS3AccessKey,
			&i.EncryptedS3SecretKey,
			&i.S3ForcePathStyle,
			&i.RetentionCount,
			&i.LastRunAt,
			&i.LastStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPgBackupSchedules = `-- name: ListPgBackupSchedules :many
SELECT id, instance_id, database_id, enabled, hour, minute, timezone, s3_endpoint, s3_region, s3_bucket, s3_prefix, encrypted_s3_access_key, encrypted_s3_secret_key, s3_force_path_style, retention_count, last_run_at, last_status, created_at, updated_at FROM pdb_backup_schedules WHERE instance_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPgBackupSchedules(ctx context.Context, instanceID uuid.UUID) ([]PdbBackupSchedule, error) {
	rows, err := q.db.Query(ctx, listPgBackupSchedules, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PdbBackupSchedule{}
	for rows.Next() {
		var i PdbBackupSchedule
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.DatabaseID,
			&i.Enabled,
			&i.Hour,
			&i.Minute,
			&i.Timezone,
			&i.S3Endpoint,
			&i.S3Region,
			&i.S3Bucket,
			&i.S3Prefix,
			&i.EncryptedS3AccessKey,
			&i.EncryptedS3SecretKey,
			&i.S3ForcePathStyle,
			&i.RetentionCount,
			&i.LastRunAt,
			&i.LastStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPgDatabases = `-- name: ListPgDatabases :many
SELECT id, instance_id, name, owner_role, created_at FROM pdb_databases WHERE instance_id = $1 ORDER BY name ASC
`

func (q *Queries) ListPgDatabases(ctx context.Context, instanceID uuid.UUID) ([]PdbDatabase, error) {
	rows, err := q.db.Query(ctx, listPgDatabases, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PdbDatabase{}
	for rows.Next() {
		var i PdbDatabase
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Name,
			&i.OwnerRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPgInstances = `-- name: ListPgInstances :many
SELECT id, name, slug, image, container_port, host_port, docker_network_host, admin_user, encrypted_admin_password, status, message, created_at, updated_at FROM pdb_instances ORDER BY created_at DESC
`

func (q *Queries) ListPgInstances(ctx context.Context) ([]PdbInstance, error) {
	rows, err := q.db.Query(ctx, listPgInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PdbInstance{}
	for rows.Next() {
		var i PdbInstance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Image,
			&i.ContainerPort,
			&i.HostPort,
			&i.DockerNetworkHost,
			&i.AdminUser,
			&i.EncryptedAdminPassword,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPgRoleGrantsByDatabase = `-- name: ListPgRoleGrantsByDatabase :many
SELECT id, role_id, database_id, is_owner FROM pdb_role_grants WHERE database_id = $1
`

func (q *Queries) ListPgRoleGrantsByDatabase(ctx context.Context, databaseID uuid.UUID) ([]PdbRoleGrant, error) {
	rows, err := q.db.Query(ctx, listPgRoleGrantsByDatabase, databaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PdbRoleGrant{}
	for rows.Next() {
		var i PdbRoleGrant
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.DatabaseID,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPgRoleGrantsByRole = `-- name: ListPgRoleGrantsByRole :many
SELECT id, role_id, database_id, is_owner FROM pdb_role_grants WHERE role_id = $1
`

func (q *Queries) ListPgRoleGrantsByRole(ctx context.Context, roleID uuid.UUID) ([]PdbRoleGrant, error) {
	rows, err := q.db.Query(ctx, listPgRoleGrantsByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PdbRoleGrant{}
	for rows.Next() {
		var i PdbRoleGrant
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.DatabaseID,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPgRoles = `-- name: ListPgRoles :many
SELECT id, instance_id, name, encrypted_password, created_at FROM pdb_roles WHERE instance_id = $1 ORDER BY name ASC
`

func (q *Queries) ListPgRoles(ctx context.Context, instanceID uuid.UUID) ([]PdbRole, error) {
	rows, err := q.db.Query(ctx, listPgRoles, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PdbRole{}
	for rows.Next() {
		var i PdbRole
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Name,
			&i.EncryptedPassword,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePgBackupSchedule = `-- name: UpdatePgBackupSchedule :one
UPDATE pdb_backup_schedules SET
    database_id = CASE WHEN $2::boolean = true THEN NULL
                       WHEN $3::uuid IS NOT NULL THEN $3::uuid
                       ELSE database_id END,
    enabled = COALESCE($4, enabled),
    hour = COALESCE($5, hour),
    minute = COALESCE($6, minute),
    timezone = COALESCE($7, timezone),
    s3_endpoint = COALESCE($8, s3_endpoint),
    s3_region = COALESCE($9, s3_region),
    s3_bucket = COALESCE($10, s3_bucket),
    s3_prefix = COALESCE($11, s3_prefix),
    encrypted_s3_access_key = COALESCE($12, encrypted_s3_access_key),
    encrypted_s3_secret_key = COALESCE($13, encrypted_s3_secret_key),
    s3_force_path_style = COALESCE($14, s3_force_path_style),
    retention_count = COALESCE($15, retention_count),
    updated_at = now()
WHERE id = $1
RETURNING id, instance_id, database_id, enabled, hour, minute, timezone, s3_endpoint, s3_region, s3_bucket, s3_prefix, encrypted_s3_access_key, encrypted_s3_secret_key, s3_force_path_style, retention_count, last_run_at, last_status, created_at, updated_at
`

type UpdatePgBackupScheduleParams struct {
	ID                   uuid.UUID   `json:"id"`
	ClearDatabaseID      pgtype.Bool `json:"clear_database_id"`
	DatabaseID           pgtype.UUID `json:"database_id"`
	Enabled              pgtype.Bool `json:"enabled"`
	Hour                 pgtype.Int4 `json:"hour"`
	Minute               pgtype.Int4 `json:"minute"`
	Timezone             pgtype.Text `json:"timezone"`
	S3Endpoint           pgtype.Text `json:"s3_endpoint"`
	S3Region             pgtype.Text `json:"s3_region"`
	S3Bucket             pgtype.Text `json:"s3_bucket"`
	S3Prefix             pgtype.Text `json:"s3_prefix"`
	EncryptedS3AccessKey []byte      `json:"encrypted_s3_access_key"`
	EncryptedS3SecretKey []byte      `json:"encrypted_s3_secret_key"`
	S3ForcePathStyle     pgtype.Bool `json:"s3_force_path_style"`
	RetentionCount       pgtype.Int4 `json:"retention_count"`
}

func (q *Queries) UpdatePgBackupSchedule(ctx context.Context, arg UpdatePgBackupScheduleParams) (PdbBackupSchedule, error) {
	row := q.db.QueryRow(ctx, updatePgBackupSchedule,
		arg.ID,
		arg.ClearDatabaseID,
		arg.DatabaseID,
		arg.Enabled,
		arg.Hour,
		arg.Minute,
		arg.Timezone,
		arg.S3Endpoint,
		arg.S3Region,
		arg.S3Bucket,
		arg.S3Prefix,
		arg.EncryptedS3AccessKey,
		arg.EncryptedS3SecretKey,
		arg.S3ForcePathStyle,
		arg.RetentionCount,
	)
	var i PdbBackupSchedule
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.DatabaseID,
		&i.Enabled,
		&i.Hour,
		&i.Minute,
		&i.Timezone,
		&i.S3Endpoint,
		&i.S3Region,
		&i.S3Bucket,
		&i.S3Prefix,
		&i.EncryptedS3AccessKey,
		&i.EncryptedS3SecretKey,
		&i.S3ForcePathStyle,
		&i.RetentionCount,
		&i.LastRunAt,
		&i.LastStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePgBackupScheduleRun = `-- name: UpdatePgBackupScheduleRun :one
UPDATE pdb_backup_schedules SET
    last_run_at = $2,
    last_status = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, instance_id, database_id, enabled, hour, minute, timezone, s3_endpoint, s3_region, s3_bucket, s3_prefix, encrypted_s3_access_key, encrypted_s3_secret_key, s3_force_path_style, retention_count, last_run_at, last_status, created_at, updated_at
`

type UpdatePgBackupScheduleRunParams struct {
	ID         uuid.UUID          `json:"id"`
	LastRunAt  pgtype.Timestamptz `json:"last_run_at"`
	LastStatus string             `json:"last_status"`
}

func (q *Queries) UpdatePgBackupScheduleRun(ctx context.Context, arg UpdatePgBackupScheduleRunParams) (PdbBackupSchedule, error) {
	row := q.db.QueryRow(ctx, updatePgBackupScheduleRun, arg.ID, arg.LastRunAt, arg.LastStatus)
	var i PdbBackupSchedule
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.DatabaseID,
		&i.Enabled,
		&i.Hour,
		&i.Minute,
		&i.Timezone,
		&i.S3Endpoint,
		&i.S3Region,
		&i.S3Bucket,
		&i.S3Prefix,
		&i.EncryptedS3AccessKey,
		&i.EncryptedS3SecretKey,
		&i.S3ForcePathStyle,
		&i.RetentionCount,
		&i.LastRunAt,
		&i.LastStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePgInstance = `-- name: UpdatePgInstance :one
UPDATE pdb_instances SET
    name = COALESCE($2, name),
    image = COALESCE($3, image),
    container_port = COALESCE($4, container_port),
    host_port = COALESCE($5, host_port),
    docker_network_host = COALESCE($6, docker_network_host),
    status = COALESCE($7, status),
    message = COALESCE($8, message),
    encrypted_admin_password = COALESCE($9, encrypted_admin_password),
    updated_at = now()
WHERE id = $1
RETURNING id, name, slug, image, container_port, host_port, docker_network_host, admin_user, encrypted_admin_password, status, message, created_at, updated_at
`

type UpdatePgInstanceParams struct {
	ID                     uuid.UUID   `json:"id"`
	Name                   pgtype.Text `json:"name"`
	Image                  pgtype.Text `json:"image"`
	ContainerPort          pgtype.Int4 `json:"container_port"`
	HostPort               pgtype.Int4 `json:"host_port"`
	DockerNetworkHost      pgtype.Bool `json:"docker_network_host"`
	Status                 pgtype.Text `json:"status"`
	Message                pgtype.Text `json:"message"`
	EncryptedAdminPassword []byte      `json:"encrypted_admin_password"`
}

func (q *Queries) UpdatePgInstance(ctx context.Context, arg UpdatePgInstanceParams) (PdbInstance, error) {
	row := q.db.QueryRow(ctx, updatePgInstance,
		arg.ID,
		arg.Name,
		arg.Image,
		arg.ContainerPort,
		arg.HostPort,
		arg.DockerNetworkHost,
		arg.Status,
		arg.Message,
		arg.EncryptedAdminPassword,
	)
	var i PdbInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Image,
		&i.ContainerPort,
		&i.HostPort,
		&i.DockerNetworkHost,
		&i.AdminUser,
		&i.EncryptedAdminPassword,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePgInstanceHostPort = `-- name: UpdatePgInstanceHostPort :one
UPDATE pdb_instances SET host_port = $2, updated_at = now() WHERE id = $1 RETURNING id, name, slug, image, container_port, host_port, docker_network_host, admin_user, encrypted_admin_password, status, message, created_at, updated_at
`

type UpdatePgInstanceHostPortParams struct {
	ID       uuid.UUID   `json:"id"`
	HostPort pgtype.Int4 `json:"host_port"`
}

func (q *Queries) UpdatePgInstanceHostPort(ctx context.Context, arg UpdatePgInstanceHostPortParams) (PdbInstance, error) {
	row := q.db.QueryRow(ctx, updatePgInstanceHostPort, arg.ID, arg.HostPort)
	var i PdbInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Image,
		&i.ContainerPort,
		&i.HostPort,
		&i.DockerNetworkHost,
		&i.AdminUser,
		&i.EncryptedAdminPassword,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePgInstanceStatus = `-- name: UpdatePgInstanceStatus :one
UPDATE pdb_instances SET status = $2, message = $3, updated_at = now() WHERE id = $1 RETURNING id, name, slug, image, container_port, host_port, docker_network_host, admin_user, encrypted_admin_password, status, message, created_at, updated_at
`

type UpdatePgInstanceStatusParams struct {
	ID      uuid.UUID `json:"id"`
	Status  string    `json:"status"`
	Message string    `json:"message"`
}

func (q *Queries) UpdatePgInstanceStatus(ctx context.Context, arg UpdatePgInstanceStatusParams) (PdbInstance, error) {
	row := q.db.QueryRow(ctx, updatePgInstanceStatus, arg.ID, arg.Status, arg.Message)
	var i PdbInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Image,
		&i.ContainerPort,
		&i.HostPort,
		&i.DockerNetworkHost,
		&i.AdminUser,
		&i.EncryptedAdminPassword,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPgRoleGrant = `-- name: UpsertPgRoleGrant :one
INSERT INTO pdb_role_grants (role_id, database_id, is_owner)
VALUES ($1, $2, $3)
ON CONFLICT (role_id, database_id) DO UPDATE SET is_owner = EXCLUDED.is_owner
RETURNING id, role_id, database_id, is_owner
`

type UpsertPgRoleGrantParams struct {
	RoleID     uuid.UUID `json:"role_id"`
	DatabaseID uuid.UUID `json:"database_id"`
	IsOwner    bool      `json:"is_owner"`
}

func (q *Queries) UpsertPgRoleGrant(ctx context.Context, arg UpsertPgRoleGrantParams) (PdbRoleGrant, error) {
	row := q.db.QueryRow(ctx, upsertPgRoleGrant, arg.RoleID, arg.DatabaseID, arg.IsOwner)
	var i PdbRoleGrant
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.DatabaseID,
		&i.IsOwner,
	)
	return i, err
}
