// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: servers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpOutboxAttempt = `-- name: BumpOutboxAttempt :exec
UPDATE servers_outbox SET
    attempts = attempts + 1,
    next_attempt_at = $2,
    last_error = $3
WHERE id = $1
`

type BumpOutboxAttemptParams struct {
	ID            int64     `json:"id"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastError     string    `json:"last_error"`
}

func (q *Queries) BumpOutboxAttempt(ctx context.Context, arg BumpOutboxAttemptParams) error {
	_, err := q.db.Exec(ctx, bumpOutboxAttempt, arg.ID, arg.NextAttemptAt, arg.LastError)
	return err
}

const countActiveRemoteNodes = `-- name: CountActiveRemoteNodes :one
SELECT count(*)::int FROM servers_nodes
WHERE deleted_at IS NULL AND connection_type <> 'local'
`

func (q *Queries) CountActiveRemoteNodes(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveRemoteNodes)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countOpenIncidentsByNode = `-- name: CountOpenIncidentsByNode :one
SELECT count(*)::int FROM servers_incidents WHERE node_id = $1 AND status = 'open'
`

func (q *Queries) CountOpenIncidentsByNode(ctx context.Context, nodeID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countOpenIncidentsByNode, nodeID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createPairingCode = `-- name: CreatePairingCode :one
INSERT INTO servers_pairing_codes (code_hash, expires_at) VALUES ($1, $2) RETURNING id, code_hash, expires_at, used_at, created_at
`

type CreatePairingCodeParams struct {
	CodeHash  []byte    `json:"code_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePairingCode(ctx context.Context, arg CreatePairingCodeParams) (ServersPairingCode, error) {
	row := q.db.QueryRow(ctx, createPairingCode, arg.CodeHash, arg.ExpiresAt)
	var i ServersPairingCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRegistrationToken = `-- name: CreateRegistrationToken :one
INSERT INTO servers_registration_tokens (installation_id, expected_node_uid, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, installation_id, expected_node_uid, token_hash, expires_at, used_at, created_at
`

type CreateRegistrationTokenParams struct {
	InstallationID  pgtype.UUID `json:"installation_id"`
	ExpectedNodeUid uuid.UUID   `json:"expected_node_uid"`
	TokenHash       []byte      `json:"token_hash"`
	ExpiresAt       time.Time   `json:"expires_at"`
}

func (q *Queries) CreateRegistrationToken(ctx context.Context, arg CreateRegistrationTokenParams) (ServersRegistrationToken, error) {
	row := q.db.QueryRow(ctx, createRegistrationToken,
		arg.InstallationID,
		arg.ExpectedNodeUid,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i ServersRegistrationToken
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.ExpectedNodeUid,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createServersCredential = `-- name: CreateServersCredential :one
INSERT INTO servers_node_credentials (
    node_id, direction, purpose, scopes, token_hash, encrypted_token
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, node_id, direction, purpose, scopes, token_hash, encrypted_token, created_at, revoked_at
`

type CreateServersCredentialParams struct {
	NodeID         uuid.UUID `json:"node_id"`
	Direction      string    `json:"direction"`
	Purpose        string    `json:"purpose"`
	Scopes         []string  `json:"scopes"`
	TokenHash      []byte    `json:"token_hash"`
	EncryptedToken []byte    `json:"encrypted_token"`
}

func (q *Queries) CreateServersCredential(ctx context.Context, arg CreateServersCredentialParams) (ServersNodeCredential, error) {
	row := q.db.QueryRow(ctx, createServersCredential,
		arg.NodeID,
		arg.Direction,
		arg.Purpose,
		arg.Scopes,
		arg.TokenHash,
		arg.EncryptedToken,
	)
	var i ServersNodeCredential
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Direction,
		&i.Purpose,
		&i.Scopes,
		&i.TokenHash,
		&i.EncryptedToken,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createServersIncident = `-- name: CreateServersIncident :one
INSERT INTO servers_incidents (
    node_id, dedup_key, event_type, resource_type, resource_id, title, last_event_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, node_id, dedup_key, event_type, resource_type, resource_id, title, status, count, first_seen_at, last_seen_at, resolved_at, last_event_id, created_at, updated_at
`

type CreateServersIncidentParams struct {
	NodeID       pgtype.UUID `json:"node_id"`
	DedupKey     string      `json:"dedup_key"`
	EventType    string      `json:"event_type"`
	ResourceType string      `json:"resource_type"`
	ResourceID   string      `json:"resource_id"`
	Title        string      `json:"title"`
	LastEventID  pgtype.UUID `json:"last_event_id"`
}

func (q *Queries) CreateServersIncident(ctx context.Context, arg CreateServersIncidentParams) (ServersIncident, error) {
	row := q.db.QueryRow(ctx, createServersIncident,
		arg.NodeID,
		arg.DedupKey,
		arg.EventType,
		arg.ResourceType,
		arg.ResourceID,
		arg.Title,
		arg.LastEventID,
	)
	var i ServersIncident
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.DedupKey,
		&i.EventType,
		&i.ResourceType,
		&i.ResourceID,
		&i.Title,
		&i.Status,
		&i.Count,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ResolvedAt,
		&i.LastEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServersInstallation = `-- name: CreateServersInstallation :one
INSERT INTO servers_installations (
    node_id, host, port, username, status, current_step, expected_node_uid,
    install_kind, panel_url, cert_email, display_name
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, node_id, host, port, username, status, current_step, ssh_fingerprint, expected_node_uid, error_code, error_message, install_kind, panel_url, cert_email, display_name, created_at, updated_at, completed_at
`

type CreateServersInstallationParams struct {
	NodeID          pgtype.UUID `json:"node_id"`
	Host            string      `json:"host"`
	Port            int32       `json:"port"`
	Username        string      `json:"username"`
	Status          string      `json:"status"`
	CurrentStep     string      `json:"current_step"`
	ExpectedNodeUid uuid.UUID   `json:"expected_node_uid"`
	InstallKind     string      `json:"install_kind"`
	PanelUrl        string      `json:"panel_url"`
	CertEmail       string      `json:"cert_email"`
	DisplayName     string      `json:"display_name"`
}

func (q *Queries) CreateServersInstallation(ctx context.Context, arg CreateServersInstallationParams) (ServersInstallation, error) {
	row := q.db.QueryRow(ctx, createServersInstallation,
		arg.NodeID,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.Status,
		arg.CurrentStep,
		arg.ExpectedNodeUid,
		arg.InstallKind,
		arg.PanelUrl,
		arg.CertEmail,
		arg.DisplayName,
	)
	var i ServersInstallation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Status,
		&i.CurrentStep,
		&i.SshFingerprint,
		&i.ExpectedNodeUid,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InstallKind,
		&i.PanelUrl,
		&i.CertEmail,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createServersNode = `-- name: CreateServersNode :one
INSERT INTO servers_nodes (
    node_uid, name, role, connection_type, base_url, status, capabilities,
    version, agent_version, last_seen_at, paired_at, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, node_uid, name, role, connection_type, base_url, status, capabilities, version, agent_version, last_seen_at, last_heartbeat_at, last_poll_at, paired_at, metadata, created_at, updated_at, deleted_at
`

type CreateServersNodeParams struct {
	NodeUid        uuid.UUID          `json:"node_uid"`
	Name           string             `json:"name"`
	Role           string             `json:"role"`
	ConnectionType string             `json:"connection_type"`
	BaseUrl        string             `json:"base_url"`
	Status         string             `json:"status"`
	Capabilities   []byte             `json:"capabilities"`
	Version        string             `json:"version"`
	AgentVersion   string             `json:"agent_version"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	PairedAt       pgtype.Timestamptz `json:"paired_at"`
	Metadata       []byte             `json:"metadata"`
}

func (q *Queries) CreateServersNode(ctx context.Context, arg CreateServersNodeParams) (ServersNode, error) {
	row := q.db.QueryRow(ctx, createServersNode,
		arg.NodeUid,
		arg.Name,
		arg.Role,
		arg.ConnectionType,
		arg.BaseUrl,
		arg.Status,
		arg.Capabilities,
		arg.Version,
		arg.AgentVersion,
		arg.LastSeenAt,
		arg.PairedAt,
		arg.Metadata,
	)
	var i ServersNode
	err := row.Scan(
		&i.ID,
		&i.NodeUid,
		&i.Name,
		&i.Role,
		&i.ConnectionType,
		&i.BaseUrl,
		&i.Status,
		&i.Capabilities,
		&i.Version,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastHeartbeatAt,
		&i.LastPollAt,
		&i.PairedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteOldDeliveredOutbox = `-- name: DeleteOldDeliveredOutbox :exec
DELETE FROM servers_outbox WHERE delivered_at IS NOT NULL AND delivered_at < $1
`

func (q *Queries) DeleteOldDeliveredOutbox(ctx context.Context, deliveredAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldDeliveredOutbox, deliveredAt)
	return err
}

const deleteOldServersSnapshots = `-- name: DeleteOldServersSnapshots :exec
DELETE FROM servers_snapshots WHERE collected_at < $1
`

func (q *Queries) DeleteOldServersSnapshots(ctx context.Context, collectedAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldServersSnapshots, collectedAt)
	return err
}

const ensureServersSettings = `-- name: EnsureServersSettings :exec
INSERT INTO servers_settings (id) VALUES (1)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) EnsureServersSettings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ensureServersSettings)
	return err
}

const getInboundCredentialByHash = `-- name: GetInboundCredentialByHash :one
SELECT id, node_id, direction, purpose, scopes, token_hash, encrypted_token, created_at, revoked_at FROM servers_node_credentials
WHERE token_hash = $1
  AND direction = 'inbound'
  AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetInboundCredentialByHash(ctx context.Context, tokenHash []byte) (ServersNodeCredential, error) {
	row := q.db.QueryRow(ctx, getInboundCredentialByHash, tokenHash)
	var i ServersNodeCredential
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Direction,
		&i.Purpose,
		&i.Scopes,
		&i.TokenHash,
		&i.EncryptedToken,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getKnownHost = `-- name: GetKnownHost :one
SELECT id, host, port, fingerprint, created_at, updated_at FROM servers_known_hosts WHERE host = $1 AND port = $2
`

type GetKnownHostParams struct {
	Host string `json:"host"`
	Port int32  `json:"port"`
}

func (q *Queries) GetKnownHost(ctx context.Context, arg GetKnownHostParams) (ServersKnownHost, error) {
	row := q.db.QueryRow(ctx, getKnownHost, arg.Host, arg.Port)
	var i ServersKnownHost
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestServersSnapshot = `-- name: GetLatestServersSnapshot :one
SELECT id, node_id, collected_at, cpu_percent, memory_used_bytes, memory_total_bytes, disk_used_percent, uptime_seconds, apps_total, apps_running, apps_unhealthy, payload FROM servers_snapshots
WHERE node_id = $1
ORDER BY collected_at DESC
LIMIT 1
`

func (q *Queries) GetLatestServersSnapshot(ctx context.Context, nodeID uuid.UUID) (ServersSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestServersSnapshot, nodeID)
	var i ServersSnapshot
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.CollectedAt,
		&i.CpuPercent,
		&i.MemoryUsedBytes,
		&i.MemoryTotalBytes,
		&i.DiskUsedPercent,
		&i.UptimeSeconds,
		&i.AppsTotal,
		&i.AppsRunning,
		&i.AppsUnhealthy,
		&i.Payload,
	)
	return i, err
}

const getLocalServersNode = `-- name: GetLocalServersNode :one
SELECT id, node_uid, name, role, connection_type, base_url, status, capabilities, version, agent_version, last_seen_at, last_heartbeat_at, last_poll_at, paired_at, metadata, created_at, updated_at, deleted_at FROM servers_nodes WHERE connection_type = 'local' AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetLocalServersNode(ctx context.Context) (ServersNode, error) {
	row := q.db.QueryRow(ctx, getLocalServersNode)
	var i ServersNode
	err := row.Scan(
		&i.ID,
		&i.NodeUid,
		&i.Name,
		&i.Role,
		&i.ConnectionType,
		&i.BaseUrl,
		&i.Status,
		&i.Capabilities,
		&i.Version,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastHeartbeatAt,
		&i.LastPollAt,
		&i.PairedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOpenIncidentByDedup = `-- name: GetOpenIncidentByDedup :one
SELECT id, node_id, dedup_key, event_type, resource_type, resource_id, title, status, count, first_seen_at, last_seen_at, resolved_at, last_event_id, created_at, updated_at FROM servers_incidents WHERE dedup_key = $1 AND status = 'open'
`

func (q *Queries) GetOpenIncidentByDedup(ctx context.Context, dedupKey string) (ServersIncident, error) {
	row := q.db.QueryRow(ctx, getOpenIncidentByDedup, dedupKey)
	var i ServersIncident
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.DedupKey,
		&i.EventType,
		&i.ResourceType,
		&i.ResourceID,
		&i.Title,
		&i.Status,
		&i.Count,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ResolvedAt,
		&i.LastEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutboundCredential = `-- name: GetOutboundCredential :one
SELECT id, node_id, direction, purpose, scopes, token_hash, encrypted_token, created_at, revoked_at FROM servers_node_credentials
WHERE node_id = $1 AND direction = 'outbound' AND revoked_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetOutboundCredential(ctx context.Context, nodeID uuid.UUID) (ServersNodeCredential, error) {
	row := q.db.QueryRow(ctx, getOutboundCredential, nodeID)
	var i ServersNodeCredential
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Direction,
		&i.Purpose,
		&i.Scopes,
		&i.TokenHash,
		&i.EncryptedToken,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getServersInstallation = `-- name: GetServersInstallation :one
SELECT id, node_id, host, port, username, status, current_step, ssh_fingerprint, expected_node_uid, error_code, error_message, install_kind, panel_url, cert_email, display_name, created_at, updated_at, completed_at FROM servers_installations WHERE id = $1
`

func (q *Queries) GetServersInstallation(ctx context.Context, id uuid.UUID) (ServersInstallation, error) {
	row := q.db.QueryRow(ctx, getServersInstallation, id)
	var i ServersInstallation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Status,
		&i.CurrentStep,
		&i.SshFingerprint,
		&i.ExpectedNodeUid,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InstallKind,
		&i.PanelUrl,
		&i.CertEmail,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getServersNode = `-- name: GetServersNode :one
SELECT id, node_uid, name, role, connection_type, base_url, status, capabilities, version, agent_version, last_seen_at, last_heartbeat_at, last_poll_at, paired_at, metadata, created_at, updated_at, deleted_at FROM servers_nodes WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetServersNode(ctx context.Context, id uuid.UUID) (ServersNode, error) {
	row := q.db.QueryRow(ctx, getServersNode, id)
	var i ServersNode
	err := row.Scan(
		&i.ID,
		&i.NodeUid,
		&i.Name,
		&i.Role,
		&i.ConnectionType,
		&i.BaseUrl,
		&i.Status,
		&i.Capabilities,
		&i.Version,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastHeartbeatAt,
		&i.LastPollAt,
		&i.PairedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getServersNodeBilling = `-- name: GetServersNodeBilling :one
SELECT id, node_id, billing_account_id, mode, provider_name, provider_url, external_service_id, cost_minor, currency, period, next_due_date, auto_renew, alert_days, comment, created_at, updated_at FROM servers_node_billing WHERE node_id = $1
`

func (q *Queries) GetServersNodeBilling(ctx context.Context, nodeID uuid.UUID) (ServersNodeBilling, error) {
	row := q.db.QueryRow(ctx, getServersNodeBilling, nodeID)
	var i ServersNodeBilling
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.BillingAccountID,
		&i.Mode,
		&i.ProviderName,
		&i.ProviderUrl,
		&i.ExternalServiceID,
		&i.CostMinor,
		&i.Currency,
		&i.Period,
		&i.NextDueDate,
		&i.AutoRenew,
		&i.AlertDays,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServersNodeByUID = `-- name: GetServersNodeByUID :one
SELECT id, node_uid, name, role, connection_type, base_url, status, capabilities, version, agent_version, last_seen_at, last_heartbeat_at, last_poll_at, paired_at, metadata, created_at, updated_at, deleted_at FROM servers_nodes WHERE node_uid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetServersNodeByUID(ctx context.Context, nodeUid uuid.UUID) (ServersNode, error) {
	row := q.db.QueryRow(ctx, getServersNodeByUID, nodeUid)
	var i ServersNode
	err := row.Scan(
		&i.ID,
		&i.NodeUid,
		&i.Name,
		&i.Role,
		&i.ConnectionType,
		&i.BaseUrl,
		&i.Status,
		&i.Capabilities,
		&i.Version,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastHeartbeatAt,
		&i.LastPollAt,
		&i.PairedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getServersSettings = `-- name: GetServersSettings :one
SELECT id, mode, node_uid, node_name, public_url, master_url, notification_mode, encrypted_master_token, created_at, updated_at FROM servers_settings WHERE id = 1
`

func (q *Queries) GetServersSettings(ctx context.Context) (ServersSetting, error) {
	row := q.db.QueryRow(ctx, getServersSettings)
	var i ServersSetting
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.NodeUid,
		&i.NodeName,
		&i.PublicUrl,
		&i.MasterUrl,
		&i.NotificationMode,
		&i.EncryptedMasterToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidPairingCodeByHash = `-- name: GetValidPairingCodeByHash :one
SELECT id, code_hash, expires_at, used_at, created_at FROM servers_pairing_codes
WHERE code_hash = $1 AND used_at IS NULL AND expires_at > now()
LIMIT 1
`

func (q *Queries) GetValidPairingCodeByHash(ctx context.Context, codeHash []byte) (ServersPairingCode, error) {
	row := q.db.QueryRow(ctx, getValidPairingCodeByHash, codeHash)
	var i ServersPairingCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidRegistrationTokenByHash = `-- name: GetValidRegistrationTokenByHash :one
SELECT id, installation_id, expected_node_uid, token_hash, expires_at, used_at, created_at FROM servers_registration_tokens
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
LIMIT 1
`

func (q *Queries) GetValidRegistrationTokenByHash(ctx context.Context, tokenHash []byte) (ServersRegistrationToken, error) {
	row := q.db.QueryRow(ctx, getValidRegistrationTokenByHash, tokenHash)
	var i ServersRegistrationToken
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.ExpectedNodeUid,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertMonitoredService = `-- name: InsertMonitoredService :one
INSERT INTO servers_monitored_services (node_id, unit_name) VALUES ($1, $2)
ON CONFLICT (node_id, unit_name) DO NOTHING
RETURNING id, node_id, unit_name, created_at
`

type InsertMonitoredServiceParams struct {
	NodeID   uuid.UUID `json:"node_id"`
	UnitName string    `json:"unit_name"`
}

func (q *Queries) InsertMonitoredService(ctx context.Context, arg InsertMonitoredServiceParams) (ServersMonitoredService, error) {
	row := q.db.QueryRow(ctx, insertMonitoredService, arg.NodeID, arg.UnitName)
	var i ServersMonitoredService
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.UnitName,
		&i.CreatedAt,
	)
	return i, err
}

const insertServersEvent = `-- name: InsertServersEvent :one
INSERT INTO servers_events (
    event_id, node_id, node_uid, event_type, severity, resource_type, resource_id,
    title, message, payload, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (event_id) DO NOTHING
RETURNING id, event_id, node_id, node_uid, event_type, severity, resource_type, resource_id, title, message, payload, occurred_at, created_at
`

type InsertServersEventParams struct {
	EventID      uuid.UUID   `json:"event_id"`
	NodeID       pgtype.UUID `json:"node_id"`
	NodeUid      pgtype.UUID `json:"node_uid"`
	EventType    string      `json:"event_type"`
	Severity     string      `json:"severity"`
	ResourceType string      `json:"resource_type"`
	ResourceID   string      `json:"resource_id"`
	Title        string      `json:"title"`
	Message      string      `json:"message"`
	Payload      []byte      `json:"payload"`
	OccurredAt   time.Time   `json:"occurred_at"`
}

func (q *Queries) InsertServersEvent(ctx context.Context, arg InsertServersEventParams) (ServersEvent, error) {
	row := q.db.QueryRow(ctx, insertServersEvent,
		arg.EventID,
		arg.NodeID,
		arg.NodeUid,
		arg.EventType,
		arg.Severity,
		arg.ResourceType,
		arg.ResourceID,
		arg.Title,
		arg.Message,
		arg.Payload,
		arg.OccurredAt,
	)
	var i ServersEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.NodeID,
		&i.NodeUid,
		&i.EventType,
		&i.Severity,
		&i.ResourceType,
		&i.ResourceID,
		&i.Title,
		&i.Message,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertServersInstallationLog = `-- name: InsertServersInstallationLog :one
INSERT INTO servers_installation_logs (installation_id, level, message)
VALUES ($1, $2, $3)
RETURNING id, installation_id, level, message, created_at
`

type InsertServersInstallationLogParams struct {
	InstallationID uuid.UUID `json:"installation_id"`
	Level          string    `json:"level"`
	Message        string    `json:"message"`
}

func (q *Queries) InsertServersInstallationLog(ctx context.Context, arg InsertServersInstallationLogParams) (ServersInstallationLog, error) {
	row := q.db.QueryRow(ctx, insertServersInstallationLog, arg.InstallationID, arg.Level, arg.Message)
	var i ServersInstallationLog
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Level,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const insertServersOutbox = `-- name: InsertServersOutbox :one
INSERT INTO servers_outbox (event_id, payload) VALUES ($1, $2)
ON CONFLICT (event_id) DO NOTHING
RETURNING id, event_id, payload, attempts, next_attempt_at, delivered_at, last_error, created_at
`

type InsertServersOutboxParams struct {
	EventID uuid.UUID `json:"event_id"`
	Payload []byte    `json:"payload"`
}

func (q *Queries) InsertServersOutbox(ctx context.Context, arg InsertServersOutboxParams) (ServersOutbox, error) {
	row := q.db.QueryRow(ctx, insertServersOutbox, arg.EventID, arg.Payload)
	var i ServersOutbox
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Payload,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const insertServersSnapshot = `-- name: InsertServersSnapshot :one
INSERT INTO servers_snapshots (
    node_id, collected_at, cpu_percent, memory_used_bytes, memory_total_bytes,
    disk_used_percent, uptime_seconds, apps_total, apps_running, apps_unhealthy, payload
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, node_id, collected_at, cpu_percent, memory_used_bytes, memory_total_bytes, disk_used_percent, uptime_seconds, apps_total, apps_running, apps_unhealthy, payload
`

type InsertServersSnapshotParams struct {
	NodeID           uuid.UUID     `json:"node_id"`
	CollectedAt      time.Time     `json:"collected_at"`
	CpuPercent       pgtype.Float8 `json:"cpu_percent"`
	MemoryUsedBytes  pgtype.Int8   `json:"memory_used_bytes"`
	MemoryTotalBytes pgtype.Int8   `json:"memory_total_bytes"`
	DiskUsedPercent  pgtype.Float8 `json:"disk_used_percent"`
	UptimeSeconds    pgtype.Int8   `json:"uptime_seconds"`
	AppsTotal        pgtype.Int4   `json:"apps_total"`
	AppsRunning      pgtype.Int4   `json:"apps_running"`
	AppsUnhealthy    pgtype.Int4   `json:"apps_unhealthy"`
	Payload          []byte        `json:"payload"`
}

func (q *Queries) InsertServersSnapshot(ctx context.Context, arg InsertServersSnapshotParams) (ServersSnapshot, error) {
	row := q.db.QueryRow(ctx, insertServersSnapshot,
		arg.NodeID,
		arg.CollectedAt,
		arg.CpuPercent,
		arg.MemoryUsedBytes,
		arg.MemoryTotalBytes,
		arg.DiskUsedPercent,
		arg.UptimeSeconds,
		arg.AppsTotal,
		arg.AppsRunning,
		arg.AppsUnhealthy,
		arg.Payload,
	)
	var i ServersSnapshot
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.CollectedAt,
		&i.CpuPercent,
		&i.MemoryUsedBytes,
		&i.MemoryTotalBytes,
		&i.DiskUsedPercent,
		&i.UptimeSeconds,
		&i.AppsTotal,
		&i.AppsRunning,
		&i.AppsUnhealthy,
		&i.Payload,
	)
	return i, err
}

const listBarnNodes = `-- name: ListBarnNodes :many
SELECT id, node_uid, name, role, connection_type, base_url, status, capabilities, version, agent_version, last_seen_at, last_heartbeat_at, last_poll_at, paired_at, metadata, created_at, updated_at, deleted_at FROM servers_nodes
WHERE deleted_at IS NULL AND connection_type = 'barn'
`

func (q *Queries) ListBarnNodes(ctx context.Context) ([]ServersNode, error) {
	rows, err := q.db.Query(ctx, listBarnNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServersNode{}
	for rows.Next() {
		var i ServersNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeUid,
			&i.Name,
			&i.Role,
			&i.ConnectionType,
			&i.BaseUrl,
			&i.Status,
			&i.Capabilities,
			&i.Version,
			&i.AgentVersion,
			&i.LastSeenAt,
			&i.LastHeartbeatAt,
			&i.LastPollAt,
			&i.PairedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitoredServices = `-- name: ListMonitoredServices :many
SELECT id, node_id, unit_name, created_at FROM servers_monitored_services WHERE node_id = $1 ORDER BY unit_name
`

func (q *Queries) ListMonitoredServices(ctx context.Context, nodeID uuid.UUID) ([]ServersMonitoredService, error) {
	rows, err := q.db.Query(ctx, listMonitoredServices, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServersMonitoredService{}
	for rows.Next() {
		var i ServersMonitoredService
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.UnitName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenServersIncidents = `-- name: ListOpenServersIncidents :many
SELECT id, node_id, dedup_key, event_type, resource_type, resource_id, title, status, count, first_seen_at, last_seen_at, resolved_at, last_event_id, created_at, updated_at FROM servers_incidents WHERE status = 'open' ORDER BY last_seen_at DESC
`

func (q *Queries) ListOpenServersIncidents(ctx context.Context) ([]ServersIncident, error) {
	rows, err := q.db.Query(ctx, listOpenServersIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServersIncident{}
	for rows.Next() {
		var i ServersIncident
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.DedupKey,
			&i.EventType,
			&i.ResourceType,
			&i.ResourceID,
			&i.Title,
			&i.Status,
			&i.Count,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.LastEventID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenServersIncidentsByNode = `-- name: ListOpenServersIncidentsByNode :many
SELECT id, node_id, dedup_key, event_type, resource_type, resource_id, title, status, count, first_seen_at, last_seen_at, resolved_at, last_event_id, created_at, updated_at FROM servers_incidents WHERE node_id = $1 AND status = 'open' ORDER BY last_seen_at DESC
`

func (q *Queries) ListOpenServersIncidentsByNode(ctx context.Context, nodeID pgtype.UUID) ([]ServersIncident, error) {
	rows, err := q.db.Query(ctx, listOpenServersIncidentsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServersIncident{}
	for rows.Next() {
		var i ServersIncident
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.DedupKey,
			&i.EventType,
			&i.ResourceType,
			&i.ResourceID,
			&i.Title,
			&i.Status,
			&i.Count,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.LastEventID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOutbox = `-- name: ListPendingOutbox :many
SELECT id, event_id, payload, attempts, next_attempt_at, delivered_at, last_error, created_at FROM servers_outbox
WHERE delivered_at IS NULL AND next_attempt_at <= now()
ORDER BY next_attempt_at ASC
LIMIT $1
`

func (q *Queries) ListPendingOutbox(ctx context.Context, limit int32) ([]ServersOutbox, error) {
	rows, err := q.db.Query(ctx, listPendingOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServersOutbox{}
	for rows.Next() {
		var i ServersOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Payload,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersEvents = `-- name: ListServersEvents :many
SELECT id, event_id, node_id, node_uid, event_type, severity, resource_type, resource_id, title, message, payload, occurred_at, created_at FROM servers_events
ORDER BY occurred_at DESC
LIMIT $1 OFFSET $2
`

type ListServersEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListServersEvents(ctx context.Context, arg ListServersEventsParams) ([]ServersEvent, error) {
	rows, err := q.db.Query(ctx, listServersEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServersEvent{}
	for rows.Next() {
		var i ServersEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.NodeID,
			&i.NodeUid,
			&i.EventType,
			&i.Severity,
			&i.ResourceType,
			&i.ResourceID,
			&i.Title,
			&i.Message,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersEventsByNode = `-- name: ListServersEventsByNode :many
SELECT id, event_id, node_id, node_uid, event_type, severity, resource_type, resource_id, title, message, payload, occurred_at, created_at FROM servers_events
WHERE node_id = $1
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type ListServersEventsByNodeParams struct {
	NodeID pgtype.UUID `json:"node_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListServersEventsByNode(ctx context.Context, arg ListServersEventsByNodeParams) ([]ServersEvent, error) {
	rows, err := q.db.Query(ctx, listServersEventsByNode, arg.NodeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServersEvent{}
	for rows.Next() {
		var i ServersEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.NodeID,
			&i.NodeUid,
			&i.EventType,
			&i.Severity,
			&i.ResourceType,
			&i.ResourceID,
			&i.Title,
			&i.Message,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersInstallationLogs = `-- name: ListServersInstallationLogs :many
SELECT id, installation_id, level, message, created_at FROM servers_installation_logs
WHERE installation_id = $1 AND id > $2
ORDER BY id ASC
LIMIT $3
`

type ListServersInstallationLogsParams struct {
	InstallationID uuid.UUID `json:"installation_id"`
	ID             int64     `json:"id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListServersInstallationLogs(ctx context.Context, arg ListServersInstallationLogsParams) ([]ServersInstallationLog, error) {
	rows, err := q.db.Query(ctx, listServersInstallationLogs, arg.InstallationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServersInstallationLog{}
	for rows.Next() {
		var i ServersInstallationLog
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.Level,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersNodeBilling = `-- name: ListServersNodeBilling :many
SELECT id, node_id, billing_account_id, mode, provider_name, provider_url, external_service_id, cost_minor, currency, period, next_due_date, auto_renew, alert_days, comment, created_at, updated_at FROM servers_node_billing
`

func (q *Queries) ListServersNodeBilling(ctx context.Context) ([]ServersNodeBilling, error) {
	rows, err := q.db.Query(ctx, listServersNodeBilling)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServersNodeBilling{}
	for rows.Next() {
		var i ServersNodeBilling
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.BillingAccountID,
			&i.Mode,
			&i.ProviderName,
			&i.ProviderUrl,
			&i.ExternalServiceID,
			&i.CostMinor,
			&i.Currency,
			&i.Period,
			&i.NextDueDate,
			&i.AutoRenew,
			&i.AlertDays,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersNodes = `-- name: ListServersNodes :many
SELECT id, node_uid, name, role, connection_type, base_url, status, capabilities, version, agent_version, last_seen_at, last_heartbeat_at, last_poll_at, paired_at, metadata, created_at, updated_at, deleted_at FROM servers_nodes
WHERE deleted_at IS NULL
ORDER BY
    CASE status WHEN 'offline' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END,
    CASE role WHEN 'master' THEN 0 ELSE 1 END,
    name ASC
`

func (q *Queries) ListServersNodes(ctx context.Context) ([]ServersNode, error) {
	rows, err := q.db.Query(ctx, listServersNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServersNode{}
	for rows.Next() {
		var i ServersNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeUid,
			&i.Name,
			&i.Role,
			&i.ConnectionType,
			&i.BaseUrl,
			&i.Status,
			&i.Capabilities,
			&i.Version,
			&i.AgentVersion,
			&i.LastSeenAt,
			&i.LastHeartbeatAt,
			&i.LastPollAt,
			&i.PairedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxDelivered = `-- name: MarkOutboxDelivered :exec
UPDATE servers_outbox SET delivered_at = now(), last_error = '' WHERE id = $1
`

func (q *Queries) MarkOutboxDelivered(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxDelivered, id)
	return err
}

const markPairingCodeUsed = `-- name: MarkPairingCodeUsed :exec
UPDATE servers_pairing_codes SET used_at = now() WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) MarkPairingCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPairingCodeUsed, id)
	return err
}

const markRegistrationTokenUsed = `-- name: MarkRegistrationTokenUsed :exec
UPDATE servers_registration_tokens SET used_at = now() WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) MarkRegistrationTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRegistrationTokenUsed, id)
	return err
}

const replaceMonitoredServices = `-- name: ReplaceMonitoredServices :exec
DELETE FROM servers_monitored_services WHERE node_id = $1
`

func (q *Queries) ReplaceMonitoredServices(ctx context.Context, nodeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, replaceMonitoredServices, nodeID)
	return err
}

const resolveServersIncident = `-- name: ResolveServersIncident :one
UPDATE servers_incidents SET
    status = 'resolved',
    resolved_at = now(),
    last_event_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, node_id, dedup_key, event_type, resource_type, resource_id, title, status, count, first_seen_at, last_seen_at, resolved_at, last_event_id, created_at, updated_at
`

type ResolveServersIncidentParams struct {
	ID          uuid.UUID   `json:"id"`
	LastEventID pgtype.UUID `json:"last_event_id"`
}

func (q *Queries) ResolveServersIncident(ctx context.Context, arg ResolveServersIncidentParams) (ServersIncident, error) {
	row := q.db.QueryRow(ctx, resolveServersIncident, arg.ID, arg.LastEventID)
	var i ServersIncident
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.DedupKey,
		&i.EventType,
		&i.ResourceType,
		&i.ResourceID,
		&i.Title,
		&i.Status,
		&i.Count,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ResolvedAt,
		&i.LastEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeNodeCredentials = `-- name: RevokeNodeCredentials :exec
UPDATE servers_node_credentials SET revoked_at = now()
WHERE node_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeNodeCredentials(ctx context.Context, nodeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeNodeCredentials, nodeID)
	return err
}

const softDeleteServersNode = `-- name: SoftDeleteServersNode :exec
UPDATE servers_nodes SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteServersNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteServersNode, id)
	return err
}

const touchServersIncident = `-- name: TouchServersIncident :one
UPDATE servers_incidents SET
    count = count + 1,
    last_seen_at = now(),
    last_event_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, node_id, dedup_key, event_type, resource_type, resource_id, title, status, count, first_seen_at, last_seen_at, resolved_at, last_event_id, created_at, updated_at
`

type TouchServersIncidentParams struct {
	ID          uuid.UUID   `json:"id"`
	LastEventID pgtype.UUID `json:"last_event_id"`
}

func (q *Queries) TouchServersIncident(ctx context.Context, arg TouchServersIncidentParams) (ServersIncident, error) {
	row := q.db.QueryRow(ctx, touchServersIncident, arg.ID, arg.LastEventID)
	var i ServersIncident
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.DedupKey,
		&i.EventType,
		&i.ResourceType,
		&i.ResourceID,
		&i.Title,
		&i.Status,
		&i.Count,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ResolvedAt,
		&i.LastEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServersInstallation = `-- name: UpdateServersInstallation :one
UPDATE servers_installations SET
    status = $2,
    current_step = $3,
    ssh_fingerprint = CASE WHEN $6::text = '' THEN ssh_fingerprint ELSE $6::text END,
    node_id = COALESCE($7, node_id),
    error_code = $4,
    error_message = $5,
    completed_at = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, node_id, host, port, username, status, current_step, ssh_fingerprint, expected_node_uid, error_code, error_message, install_kind, panel_url, cert_email, display_name, created_at, updated_at, completed_at
`

type UpdateServersInstallationParams struct {
	ID             uuid.UUID          `json:"id"`
	Status         string             `json:"status"`
	CurrentStep    string             `json:"current_step"`
	ErrorCode      string             `json:"error_code"`
	ErrorMessage   string             `json:"error_message"`
	SshFingerprint string             `json:"ssh_fingerprint"`
	NodeID         pgtype.UUID        `json:"node_id"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateServersInstallation(ctx context.Context, arg UpdateServersInstallationParams) (ServersInstallation, error) {
	row := q.db.QueryRow(ctx, updateServersInstallation,
		arg.ID,
		arg.Status,
		arg.CurrentStep,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.SshFingerprint,
		arg.NodeID,
		arg.CompletedAt,
	)
	var i ServersInstallation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Status,
		&i.CurrentStep,
		&i.SshFingerprint,
		&i.ExpectedNodeUid,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InstallKind,
		&i.PanelUrl,
		&i.CertEmail,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateServersNode = `-- name: UpdateServersNode :one
UPDATE servers_nodes SET
    name = $2,
    base_url = $3,
    metadata = $4,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, node_uid, name, role, connection_type, base_url, status, capabilities, version, agent_version, last_seen_at, last_heartbeat_at, last_poll_at, paired_at, metadata, created_at, updated_at, deleted_at
`

type UpdateServersNodeParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	BaseUrl  string    `json:"base_url"`
	Metadata []byte    `json:"metadata"`
}

func (q *Queries) UpdateServersNode(ctx context.Context, arg UpdateServersNodeParams) (ServersNode, error) {
	row := q.db.QueryRow(ctx, updateServersNode,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.Metadata,
	)
	var i ServersNode
	err := row.Scan(
		&i.ID,
		&i.NodeUid,
		&i.Name,
		&i.Role,
		&i.ConnectionType,
		&i.BaseUrl,
		&i.Status,
		&i.Capabilities,
		&i.Version,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastHeartbeatAt,
		&i.LastPollAt,
		&i.PairedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateServersNodeHeartbeat = `-- name: UpdateServersNodeHeartbeat :one
UPDATE servers_nodes SET
    status = $2,
    last_seen_at = $3,
    last_heartbeat_at = $3,
    version = CASE WHEN $4::text = '' THEN version ELSE $4::text END,
    agent_version = CASE WHEN $5::text = '' THEN agent_version ELSE $5::text END,
    updated_at = now()
WHERE id = $1
RETURNING id, node_uid, name, role, connection_type, base_url, status, capabilities, version, agent_version, last_seen_at, last_heartbeat_at, last_poll_at, paired_at, metadata, created_at, updated_at, deleted_at
`

type UpdateServersNodeHeartbeatParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       string             `json:"status"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	Version      string             `json:"version"`
	AgentVersion string             `json:"agent_version"`
}

func (q *Queries) UpdateServersNodeHeartbeat(ctx context.Context, arg UpdateServersNodeHeartbeatParams) (ServersNode, error) {
	row := q.db.QueryRow(ctx, updateServersNodeHeartbeat,
		arg.ID,
		arg.Status,
		arg.LastSeenAt,
		arg.Version,
		arg.AgentVersion,
	)
	var i ServersNode
	err := row.Scan(
		&i.ID,
		&i.NodeUid,
		&i.Name,
		&i.Role,
		&i.ConnectionType,
		&i.BaseUrl,
		&i.Status,
		&i.Capabilities,
		&i.Version,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastHeartbeatAt,
		&i.LastPollAt,
		&i.PairedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateServersNodePoll = `-- name: UpdateServersNodePoll :one
UPDATE servers_nodes SET
    status = $2,
    last_seen_at = $3,
    last_poll_at = $3,
    version = CASE WHEN $4::text = '' THEN version ELSE $4::text END,
    capabilities = COALESCE($5::jsonb, capabilities),
    updated_at = now()
WHERE id = $1
RETURNING id, node_uid, name, role, connection_type, base_url, status, capabilities, version, agent_version, last_seen_at, last_heartbeat_at, last_poll_at, paired_at, metadata, created_at, updated_at, deleted_at
`

type UpdateServersNodePollParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       string             `json:"status"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	Version      string             `json:"version"`
	Capabilities []byte             `json:"capabilities"`
}

func (q *Queries) UpdateServersNodePoll(ctx context.Context, arg UpdateServersNodePollParams) (ServersNode, error) {
	row := q.db.QueryRow(ctx, updateServersNodePoll,
		arg.ID,
		arg.Status,
		arg.LastSeenAt,
		arg.Version,
		arg.Capabilities,
	)
	var i ServersNode
	err := row.Scan(
		&i.ID,
		&i.NodeUid,
		&i.Name,
		&i.Role,
		&i.ConnectionType,
		&i.BaseUrl,
		&i.Status,
		&i.Capabilities,
		&i.Version,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastHeartbeatAt,
		&i.LastPollAt,
		&i.PairedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateServersNodeStatus = `-- name: UpdateServersNodeStatus :exec
UPDATE servers_nodes SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateServersNodeStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateServersNodeStatus(ctx context.Context, arg UpdateServersNodeStatusParams) error {
	_, err := q.db.Exec(ctx, updateServersNodeStatus, arg.ID, arg.Status)
	return err
}

const updateServersSettings = `-- name: UpdateServersSettings :one
UPDATE servers_settings SET
    mode = $2,
    node_name = $3,
    public_url = $4,
    master_url = $5,
    notification_mode = $6,
    encrypted_master_token = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, mode, node_uid, node_name, public_url, master_url, notification_mode, encrypted_master_token, created_at, updated_at
`

type UpdateServersSettingsParams struct {
	ID                   int32  `json:"id"`
	Mode                 string `json:"mode"`
	NodeName             string `json:"node_name"`
	PublicUrl            string `json:"public_url"`
	MasterUrl            string `json:"master_url"`
	NotificationMode     string `json:"notification_mode"`
	EncryptedMasterToken []byte `json:"encrypted_master_token"`
}

func (q *Queries) UpdateServersSettings(ctx context.Context, arg UpdateServersSettingsParams) (ServersSetting, error) {
	row := q.db.QueryRow(ctx, updateServersSettings,
		arg.ID,
		arg.Mode,
		arg.NodeName,
		arg.PublicUrl,
		arg.MasterUrl,
		arg.NotificationMode,
		arg.EncryptedMasterToken,
	)
	var i ServersSetting
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.NodeUid,
		&i.NodeName,
		&i.PublicUrl,
		&i.MasterUrl,
		&i.NotificationMode,
		&i.EncryptedMasterToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertKnownHost = `-- name: UpsertKnownHost :one
INSERT INTO servers_known_hosts (host, port, fingerprint)
VALUES ($1, $2, $3)
ON CONFLICT (host, port) DO UPDATE SET
    fingerprint = EXCLUDED.fingerprint,
    updated_at = now()
RETURNING id, host, port, fingerprint, created_at, updated_at
`

type UpsertKnownHostParams struct {
	Host        string `json:"host"`
	Port        int32  `json:"port"`
	Fingerprint string `json:"fingerprint"`
}

func (q *Queries) UpsertKnownHost(ctx context.Context, arg UpsertKnownHostParams) (ServersKnownHost, error) {
	row := q.db.QueryRow(ctx, upsertKnownHost, arg.Host, arg.Port, arg.Fingerprint)
	var i ServersKnownHost
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertServersNodeBilling = `-- name: UpsertServersNodeBilling :one
INSERT INTO servers_node_billing (
    node_id, billing_account_id, mode, provider_name, provider_url, external_service_id,
    cost_minor, currency, period, next_due_date, auto_renew, alert_days, comment
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (node_id) DO UPDATE SET
    billing_account_id = EXCLUDED.billing_account_id,
    mode = EXCLUDED.mode,
    provider_name = EXCLUDED.provider_name,
    provider_url = EXCLUDED.provider_url,
    external_service_id = EXCLUDED.external_service_id,
    cost_minor = EXCLUDED.cost_minor,
    currency = EXCLUDED.currency,
    period = EXCLUDED.period,
    next_due_date = EXCLUDED.next_due_date,
    auto_renew = EXCLUDED.auto_renew,
    alert_days = EXCLUDED.alert_days,
    comment = EXCLUDED.comment,
    updated_at = now()
RETURNING id, node_id, billing_account_id, mode, provider_name, provider_url, external_service_id, cost_minor, currency, period, next_due_date, auto_renew, alert_days, comment, created_at, updated_at
`

type UpsertServersNodeBillingParams struct {
	NodeID            uuid.UUID   `json:"node_id"`
	BillingAccountID  pgtype.UUID `json:"billing_account_id"`
	Mode              string      `json:"mode"`
	ProviderName      string      `json:"provider_name"`
	ProviderUrl       string      `json:"provider_url"`
	ExternalServiceID string      `json:"external_service_id"`
	CostMinor         int64       `json:"cost_minor"`
	Currency          string      `json:"currency"`
	Period            string      `json:"period"`
	NextDueDate       pgtype.Date `json:"next_due_date"`
	AutoRenew         bool        `json:"auto_renew"`
	AlertDays         int32       `json:"alert_days"`
	Comment           string      `json:"comment"`
}

func (q *Queries) UpsertServersNodeBilling(ctx context.Context, arg UpsertServersNodeBillingParams) (ServersNodeBilling, error) {
	row := q.db.QueryRow(ctx, upsertServersNodeBilling,
		arg.NodeID,
		arg.BillingAccountID,
		arg.Mode,
		arg.ProviderName,
		arg.ProviderUrl,
		arg.ExternalServiceID,
		arg.CostMinor,
		arg.Currency,
		arg.Period,
		arg.NextDueDate,
		arg.AutoRenew,
		arg.AlertDays,
		arg.Comment,
	)
	var i ServersNodeBilling
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.BillingAccountID,
		&i.Mode,
		&i.ProviderName,
		&i.ProviderUrl,
		&i.ExternalServiceID,
		&i.CostMinor,
		&i.Currency,
		&i.Period,
		&i.NextDueDate,
		&i.AutoRenew,
		&i.AlertDays,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
